### ISSUE TITLE
calendar invite accept/cancel does not work (well)

### ISSUE THREAD

**Issue by YoogleMarcus** [protz/thunderbird-conversations#961] opened 2015-05-22 15:37 UTC
When I get a meeting invite, or an event cancellation, the message contains the "delete" or "accept" or ... buttons.
In classic view, clicking on those buttons do the expected thing, and the button disappears.
But in conversations view, clicking on the buttons sometime work, sometime does nothing, and other times I've seen it do something after as much as a minute delay.

For the most part, the ones I'm having difficulties are with calendar event from exchange/davmail setup.

**Comment by protz** [comment] 2015-05-26 02:11
Any errors in Tools > Error Console? I'm not using Lightning myself so chances of me fixing this are very low, unfortunately.

**Comment by blerner** [comment] 2015-06-27 13:22
I think I tripped over this yesterday, and filed a [bug 1177719](https://bugzilla.mozilla.org/show_bug.cgi?id=1177719) for it.  There is some error console output for me: `ltnImipBar.itipItem is null`, which (if comment 3 in that bug is right) can happen due to a race condition, and which could easily crash the invitation accept/cancel step.

**Comment by blerner** [comment] 2015-06-27 13:22
Issue #955 also seems like a potential dupe of this issue...

**Comment by protz** [comment] 2015-06-28 19:44
Suggested fix in https://bugzilla.mozilla.org/show_bug.cgi?id=1177719#c3

**Comment by Standard8** [comment] 2020-03-01 11:12
We've recently redone how the UI handles some of the work. I've also not heard complaints about this recently.

Therefore I'll close this out, but if it is still happening in the latest Thunderbird (68) and Conversations (3.0.16) versions, please feel free to reopen or file a new issue.

**Closed** 2020-05-16 21:21 UTC
Labels: bug
