### ISSUE TITLE
Quick-Reply is not encrypted without any warning

### ISSUE THREAD

**Issue by RalfJung** [protz/thunderbird-conversations#1015] opened 2015-10-08 11:56 UTC
With Conversations having some kind of support for Enigmail for decryption and signature verification, I kind of assumed that it would also have support for encryption. That, however, does not seem to be the case: When I use quick-reply to send a mail to someone of whom I have a trusted key, the mail still goes out unencrypted. I learned this by accidentally sending a mail in unencrypted form that I wanted to be encrypted. (Lucky enough, there was no personal or private data in that mail.)

Conversations could at the least inform users (maybe as part of its setup process) that it will never encrypt quick-replies. Even better, of course, would be extending the enigmail support to also cover sending :D

**Comment by protz** [comment] 2015-10-08 16:33
It uses the default preferences for your account.

There was an issue about that just a few weeks ago. Can you mark as a 
duplicate of #791?

Thanks,

Jonathan

**Comment by RalfJung** [comment] 2015-10-08 17:40
> It uses the default preferences for your account.

I have Enigmail configured to automatically encrypt mail from this account to verified keys. When I use "manual" reply, the mail gets encrypted without any further interaction from my side.
So, using the default does not work here, or I don't know what default it is using.

Should I still mark as dupe?

**Comment by protz** [comment] 2015-10-08 17:42
No, just cross-reference the issues. That's probably a wrong 
interpretation of "default" in the code.

Enigmail support is very primitive...

**Comment by azrdev** [comment] 2015-11-20 13:11
Using TB 38 and Conversations 2.10, Quick replies are not even signed, although they should be, as far as I've configured.

**Comment by kehugter** [comment] 2016-08-18 22:14
Same issue, quick replies aren't signed. I'm quite sure they were not long ago tho.

**Comment by Standard8** [comment] 2017-10-01 13:46
Looks like this was fixed by #1029 but didn't get closed when that was merged. If there's more missing, please feel free to file new issues.

**Closed by Standard8** 2017-10-01 13:46 UTC
Labels: bug
