### ISSUE TITLE
Body not displayed for S/MIME signed messages

### ISSUE THREAD

**Issue by azrdev** [protz/thunderbird-conversations#1092] opened 2016-05-26 17:08 UTC
Mails from a certain contact of mine usually have the following body:

```
Content-Type: multipart/signed;
 boundary="=_MailMate_7575846C-172C-4EB0-A42D-0C90D9D4FF5E_="; micalg=sha1;
 protocol="application/pkcs7-signature"
(last header line)

This is an S/MIME signed message (RFC 5652 and 5751).

--=_MailMate_7575846C-172C-4EB0-A42D-0C90D9D4FF5E_=
Content-Type: multipart/mixed;
 boundary="=_MailMate_4A5B0074-2492-490F-A37F-7CBD4337AE09_="


--=_MailMate_4A5B0074-2492-490F-A37F-7CBD4337AE09_=
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable
```

When opening such a message in Conversations view, nothing of the content is displayed, only the header line and the "signed" button/icon. Below, nothing is shown.

**Comment by cy8aer** [comment] 2016-06-19 16:46
+1

**Comment by SimJoSt** [comment] 2016-06-20 14:27
I have the same problem.
I tried the newest version (https://jonathan.protzenko.fr/thunderbird-conversations/) and have not run into this error again. I'll keep you up to date.

**Comment by Stormray** [comment] 2016-06-22 00:05
Same for me. In the error console of Thunderbird is logged: 
Timestamp: 22.06.2016 01:57:41
Warning: unreachable code after return statement
Source file: chrome://conversations/content/js/jquery.tokeninput.js
Row: 470

**Comment by HenriWahl** [comment] 2016-06-27 07:21
@SimJoSt which version did you test? https://jonathan.protzenko.fr/thunderbird-conversations/201605290911-master.xpi ? Did not work here :-(

**Comment by davidhrbac** [comment] 2016-07-19 11:02
The very same for me. The latest https://jonathan.protzenko.fr/thunderbird-conversations/201605290911-master.xpi does not work for me. I can see the message body in preview. Clicking on the message displays no body just the attachments.

**Comment by SimJoSt** [comment] 2016-07-22 13:07
@HenriWahl Thunderbird says it's using the version 2.12pre of the addon. I believe I downloaded the master, but I cannot tell you for sure anymore.

**Comment by HenriWahl** [comment] 2016-07-23 20:19
@SimJoSt I use a version called 2.11.4 - the latest available at https://jonathan.protzenko.fr/thunderbird-conversations/. Where did you get yours?

**Comment by SimJoSt** [comment] 2016-07-28 12:07
@HenriWahl The same place you did. I took the file called "master".

I encountered the problem again with several mails again, though not that often like before.

**Comment by protz** [comment] 2016-12-31 16:22
If you can provide some extra hints, e.g. meaningful errors in the error console, or if you can investigate further, that'd be really helpful. I don't use S/MIME myself so setting up a test environment is hard...

**Comment by HenriWahl** [comment] 2017-01-02 08:33
Zeitstempel: 02.01.2017 09:32:18
Warnung: unreachable code after return statement
Quelldatei: chrome://conversations/content/js/jquery.tokeninput.js
Zeile: 470

Zeitstempel: 02.01.2017 09:32:23
Warnung: getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented.
Quelldatei: chrome://conversations/content/js/jquery-1.6.4.min.js
Zeile: 3

**Comment by protz** [comment] 2017-01-02 10:12
Thanks; sadly, these messages are irrelevant.

It sounds like I need to debug further; I have very little incentive to setup a test S/MIME environment, esp. given that no one ever sends me S/MIME mail... so any help for this issue would be most welcome.

Thanks!

**Comment by HenriWahl** [comment] 2017-01-02 10:14
I can send you a S/MIME mail... :-)

**Comment by protz** [comment] 2017-01-02 10:22
That'd be helpful, but I don't even have a certificate setup. I think I 
had it setup on a previous machine but of course these things don't roam...

**Comment by kfl** [comment] 2017-01-04 11:39
This might not be conversations' fault. I had the same problem (and found this issue via Google), but found that the culprit was Enigmail.

For me the problem goes away when using a nightly build of Enigmail from <https://www.enigmail.net/index.php/en/download/nightly-build> (identifying itself as v. 2.0a1pre).

Just thought that I would update here for others ending up here via Google.

And @protz Thanks for the conversations plugin!

**Comment by HenriWahl** [comment] 2017-01-04 13:46
Interesting... I use Enigmail too. But it should not care about S/MIME but PGP, right?

**Comment by HenriWahl** [comment] 2017-01-04 14:00
Incredible... thanks @kfl for the hint and @protz for conversations plugin! Finally I see conversations again,

**Comment by protz** [comment] 2017-01-04 14:10
So it does the right thing? Incredible! Closing this issue.

**Closed by protz** 2017-01-04 14:10 UTC
Labels: bug, investigate

**Comment by kfl** [comment] 2017-01-04 18:42
For those who are interested here is a link to (one of) the relevant messages on the Enigmail mailing list <https://admin.hostpoint.ch/pipermail/enigmail-users_enigmail.net/2016-September/004125.html>

@HenriWahl Apparently Enigmail tries to parse the message and fails, and in that case it doesn't/didn't display anything. I also thought that Enigmail was only for PGP.

**Comment by sliwowitz** [comment] 2017-01-04 19:52
Hello, no, this doesn't help. I updated to the nightly Enigmail plugin (nw says 2.0a1pre), and S/MIME messages in conversation thread are still invisible. (TB 45.5.1, Conversations 2.11.4)

To make the messages visible, one must select one, and open in a separate window. Then all messages (or at least those signed by the same person) magically appear even in conversation windows - but that's how this bug manifested for months.

**Comment by HenriWahl** [comment] 2017-01-05 08:05
Same here... it *worked* but for no reason it stopped now too. :-(

**Comment by sliwowitz** [comment] 2017-01-10 20:47
But it seems the problem is indeed in interaction with Enigmail - if I disable the Enigmail extension, Conversations work. (not that I'd want to do that - I use both S/MIME and PGP daily)

Is there anything I can do to help debug the issue?

**Comment by SimJoSt** [comment] 2017-01-25 17:20
Same here. Nightly version of Enigmail didn't help.

**Comment by dessite** [comment] 2017-11-03 12:07
I still see this bug. Fedora 26, Thunderbird 52.4.0 (64 bit), Conversations Addon 2.13.2, Enigmail 1.9.8.3. The above workaround from @SimJoSt works for me. Tried installing Enigmail Nightly build, as a result, no message was able to load in preview (only "Loading" was displayed)

**Comment by tobiasBora** [comment] 2018-02-15 16:41
Same problem, Debian unstable, Thunderbird 52.6 (64 bits), Conversation 2.13.4, Enigmail 1.9.9.

**Comment by HenriWahl** [comment] 2018-03-28 18:39
Problem still exists on latest stable Enigmail 2.0 and Thunderbird 52.6.0 on Fedora 27.

**Comment by Black-Pixel** [comment] 2018-03-31 13:55
I had the same issue with Thunderbird 52.7.0, Enigmail 2.0, and Conversations 2.13.4 on Windows 10. 

To fix the issue I've first disabled Enigmail, removed Conversations, and re-enabled Enigmail to check if the mails still work. Then I have re-added Conversations. Everything seems fine so far and the E-Mails are being displayed properly.

I believe the issue is really the order in which the addons are added. The proper order should be Enigmail first and Conversations second.

**Comment by anderwm** [comment] 2018-06-26 15:19
Conversations still breaks signed emails for me no matter the order added/installed.
52.8.0 (64-bit) on ubuntu 18.04

**Comment by Mystixor** [comment] 2024-10-30 10:06
I hate to reactivate such an old thread however the problem still persists: S/MIME signed messages still only show an empty box. Viewing the mail in classic reader, then reopening the mail in Conversations view momentarily fixes the issue, i.e. until the next restart of Thunderbird. I do not use Enigmail or any similar add-on. Running on Win11, TB 128.4.0esr (64-bit).

**Comment by Standard8** [comment] 2024-10-30 10:23
@Mystixor please file a new issue. New issues are cheap and issues are less likely to be lost.

**Comment by Mystixor** [comment] 2024-10-30 10:27
After replying to this issue I found #2006 and as far as I can tell that is most likely the root cause of my problem, so no new issue required here.
