### ISSUE TITLE
Message pane not showing messages (due to Exquilla)

### ISSUE THREAD

**Issue by sguldemond** [protz/thunderbird-conversations#1495] opened 2020-06-12 11:16 UTC
* **Thunderbird version:**
68.8.0 (64-bit)
* **Thunderbird Conversation version:**
3.1.6
* **Operating System:**
Ubuntu 20.04 LTS x86_64
**What did you do?**
I selected an unread message from my inbox.
**What did you expect to happen?**
The message to show in de message pane
**What actually happened?**
The message was not shown, the message pane stayed empty. Only on the top right only "Forward this conversation" is shown. I can right click in the message pane to select things like reply, this works. Also the message doenst get 'read' when selecting.

The same issue occurs for both my email addresses (Gmail and Outlook). When I disable the add on my messages are shown normally.

Here I have selected a message:
![thunderbird-conversation-bug-01](https://user-images.githubusercontent.com/30954154/84497498-33691380-acaf-11ea-9364-9acb2d862af4.png)

**Comment by Standard8** [comment] 2020-06-12 11:19
Please can you go to the three bar menu -> Tools -> Developer Tools -> Error Console, and see if there are any error messages when you click a message (maybe on startup as well).

**Comment by sguldemond** [comment] 2020-06-12 11:21
It shows the following when I select a message:

```
[Exception... "JavaScript component does not have a method named: "Symbol.iterator"'JavaScript component does not have a method named: "Symbol.iterator"' when calling method: [nsISimpleEnumerator::Symbol.iterator]"  nsresult: "0x80570030 (NS_ERROR_XPC_JSOBJECT_HAS_NO_FUNCTION_NAMED)"  location: "JS frame :: chrome://messenger/content/parent/ext-addressBook.js :: quickSearch :: line 556"  data: no] ext-addressBook.js:556:49
    quickSearch chrome://messenger/content/parent/ext-addressBook.js:556
    quickSearch self-hosted:1005
    result resource://gre/modules/ExtensionParent.jsm:1139
    withPendingBrowser resource://gre/modules/ExtensionParent.jsm:770
    result resource://gre/modules/ExtensionParent.jsm:1139
    withTiming resource://gre/modules/ExtensionParent.jsm:1100
    call resource://gre/modules/ExtensionParent.jsm:1138
    InterpretGeneratorResume self-hosted:1284
    AsyncFunctionNext self-hosted:839
{…}
​
columnNumber: 1
​
fileName: "undefined"
​
lineNumber: 0
​
message: "An unexpected error occurred"
​
stack: ""
​
<prototype>: Object { … }
```

**Comment by sguldemond** [comment] 2020-06-12 11:26
When I have the add on disabled and I then enable it, it shows me the following in the error console:
```
No chrome package registered for chrome://enigmail/content/modules/constants.jsm
```

**Comment by Standard8** [comment] 2020-06-12 11:26
Do you have Exquilla or some other address book defining add-on installed? In #1492 we saw that this was caused by Exquilla having an out-of-date license.

Fundamentally, it is a Thunderbird bug as the API is failing when it shouldn't do. 

If disabling other add-ons doesn't work, please try installing this new version that should work around it (it is currently awaiting approval): https://www.thebanners.uk/conversations-3.1.7.xpi

**Comment by sguldemond** [comment] 2020-06-12 11:27
I use Exquilla yes. I will try that. Thank you for the super quick response :)

**Comment by Standard8** [comment] 2020-06-12 11:45
Hope that works. I'll leave this open for visibility for people that might be hitting this.

I've also just filed a bug on Thunderbird for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1645361

**Comment by sguldemond** [comment] 2020-06-12 13:40
Hey, you're patch works, thats great. Thanks again!

**Comment by WalZyl** [comment] 2020-06-13 12:18
I experience same issue as sguldemond reported; differently, however, that the message pane does not show the control buttons in the top-right corner: the message pane is completely empty. No Exquilla installed. This even occurs if all other add-ons are disabled. If TB conversations is disabled, TB works as expected.

Running Win10, TB 68.9.0 (64bit) an TB Conversations 3.1.9.

I inspect Error Console (screenshot). The link on the left points to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Not_defined 

the link on the right to the source code (another screenshot). Hope that gives some useful information for fixing.

![ScreenShot](https://user-images.githubusercontent.com/59749335/84568534-4ef01f00-ad80-11ea-811c-355167d1a2e6.png)
![AnotherScreenshot](https://user-images.githubusercontent.com/59749335/84568536-531c3c80-ad80-11ea-848e-e3e96ebcb188.png)

**Comment by Standard8** [comment] 2020-06-13 12:54
@WalZyl that's a different issue. I think if you have your message pane open it'll probably work for you, I think you're hiding it at times (based on where the error is added).

In any case, I've just fixed the code and improved our lint tests a bit to hopefully catch typos like that in future.

I'm closing this out now since 3.1.9 is out, and fixes the original issue.

**Closed by Standard8** 2020-06-13 12:54 UTC

**Comment by Standard8** [comment] 2020-06-14 15:07
@WalZyl I've pushed out a new version for review that should fix the error there that you've got, hopefully it'll be approved in a couple of days.

**Comment by WalZyl** [comment] 2020-06-16 20:19
3.1.13 works fine
