### ISSUE TITLE
Freezes with 3.1.6

### ISSUE THREAD

**Issue by MLopez-Ibanez** [protz/thunderbird-conversations#1490] opened 2020-06-10 11:04 UTC
* **Thunderbird version: 68.8.0**
* **Thunderbird Conversation version: 3.1.6**
* **Operating System: Linux**

**What did you do?**

Thunderbird freezes (CPU 100%) at random intervals with the add-on enabled. No freezes with the add-on disabled. Only killing the process seems to work.

**Comment by Standard8** [comment] 2020-06-10 11:09
Is this when you are doing particular things? What happens if Thunderbird just sits idle without you doing anything?

You could try having the activity manager (in the three-bar menu) and the error console (under Tools -> Developer Tools) open and seeing if they lead to any interesting reason as to why it is hanging.

**Comment by Standard8** [comment] 2020-06-10 11:36
It might also be worth trying uninstalling Conversations, restarting, then installing it again.

**Comment by Standard8** [comment] 2020-06-11 07:21
I've just been re-examining the code, unfortunately I've not found anything yet. I did notice from your log that it finishes with:

```
console.debug: Conversations.Conversation: "onItemsAdded" "GA 505d506e-4315-ce1c-7f4a-c427ef414f25@manchester.ac.uk"
console.debug: Conversations.Conversation: 8 "messages already in the conversation"
```

but doesn't have a `Appending` message after it. It is possible there were no messages to append, or it got hung before then - however I can't see any possibilities there for unbounded loops.

I'm going to add in a `No messages to append` message which might at least eliminate that bit of code (or highlight it).

I also can't see anything obvious in that extension list - all of the rest of your extensions don't seem to be interacting with the message display or lists, so we should be ok there. Though it might be worth disabling them anyway and seeing what happens.

**Comment by Standard8** [comment] 2020-06-11 09:29
I've just put a new version up for review which has those messages, I don't think it'll fix the issue though.

If you want to try it, then I've put up a copy here: https://www.thebanners.uk/conversations-3.1.7.xpi

**Comment by MLopez-Ibanez** [comment] 2020-06-11 17:29
> The other option I've just thought of is seeing if you can use the debugger in the developer toolbox to pause when you're in a hang state. The developer toolbox is run in a separate process, so you may just be able to catch it.

I'm able to pause and the debugger is responsive, but I have no idea how tell the debugger to show me a backtrace or where the current execution is. Any suggestions?

**Comment by Standard8** [comment] 2020-06-11 18:08
Normally the "call stack" is on the right, e.g. see the image below.

It might be worth trying a few especially if they look more like event things rather than other things. 

Also, if the debugger is working, you might be able to get a performance profile - go to the three dots at top right, hit settings, then enable performance. You'll need to not be on a breakpoint, of course, but you should be able to start recording and save profiles (you should be able to load and share them on https://profiler.firefox.com/).

<img width="317" alt="Screenshot 2020-06-11 at 19 03 59" src="https://user-images.githubusercontent.com/520844/84423481-6d3a0b80-ac16-11ea-8839-5bfef9c4f5c8.png">

**Comment by MLopez-Ibanez** [comment] 2020-06-11 18:19
Sorry, it seems I was wrong. I click pause but the debugger is not able to stop it. It never reaches a state as the one shown in your picture (but the debugger window is responsive, so it is not frozen). I noticed that if I wait long enough, the OOM killer always ends up killing thunderbird, so something keeps allocating memory non-stop. With the new version that you uploaded I get this output (from the debugger). Maybe the "Conversations.AssistantUI: Document is not ready (uninitialized), waiting..." is a hint?

I'll try now to selectively enable add-ons.

```
Conversations.Message: A message is selected: imap-message://****@***/INBOX#240552 message.js:538:9
FolderLoaded folder:Inbox
FolderLoaded folder:Incorporación
FolderLoaded folder:Deleted
FolderLoaded folder:Drafts
Conversations.AssistantUI: Document is not ready (uninitialized), waiting... api.js:169:9
NS_NOINTERFACE: Component returned failure code: 0x80004002 (NS_NOINTERFACE) [nsISupports.QueryInterface] stack-trace-collector.js:84
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:1541:30
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:1997:33
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:5185:53
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:5195:59
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:7377:31
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:12886:34
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:14001:51
SyntaxError: test for equality (==) mistyped as assignment (=)?
sugar.js:14005:50
ReferenceError: reference to undefined property "timeMarkerOptional"
sugar.js:5517:11
ReferenceError: reference to undefined property "timeSeparator"
sugar.js:3144:9
ReferenceError: reference to undefined property "ldml"
sugar.js:4204:7
ReferenceError: reference to undefined property "flags"
sugar.js:250:16
SyntaxError: test for equality (==) mistyped as assignment (=)?
utils.js:553:44
SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead
signatureswitch.js:748:75
SyntaxError: "0"-prefixed octal literals and octal escape sequences are deprecated; for octal literals use the "0o" prefix instead
signatureswitch.js:748:79
window.controllers/Controllers is deprecated. Do not use it for UA detection. blank
ReferenceError: assignment to undeclared variable fieldValue
mrc_compose.js:220:17
ReferenceError: assignment to undeclared variable rcp_ok
mrc_compose.js:227:1
ReferenceError: assignment to undeclared variable newHeight
mrc_compose.js:5103:9
ReferenceError: assignment to undeclared variable nb
mrc_compose.js:4725:9
FolderLoaded folder:Drafts
FolderLoaded folder:Inbox
FolderLoaded folder:Deleted
FolderLoaded folder:Incorporación
```

**Comment by MLopez-Ibanez** [comment] 2020-06-12 06:41
I disabled all addons except Lightning and Google provider and it still freezes. I noticed some additional strange behaviors. Emails not displaying while the console shows:

```
console.debug: Conversations.AssistantUI: "Intercepted message load," 0 "message(s) selected"
JavaScript strict warning: chrome://messenger/content/specialTabs.js, line 1461: ReferenceError: reference to undefined property "loadListener"
console.debug: Conversations.AssistantUI: "Intercepted message load," 0 "message(s) selected"
JavaScript strict warning: resource:///modules/gloda/gloda.js, line 2235: ReferenceError: reference to undefined property "providerName"
console.debug: Conversations.AssistantUI: "Intercepted message load," 1 "message(s) selected"
JavaScript strict warning: chrome://conversations/content/vendor/react-redux.js, line 1: ReferenceError: reference to undefined property "$$typeof"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 58: ReferenceError: reference to undefined property "childContextTypes"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 79: ReferenceError: reference to undefined property "type"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 127: ReferenceError: reference to undefined property "__reactInternalSnapshotBeforeUpdate"
JavaScript strict warning: chrome://conversations/content/vendor/react.js, line 15: ReferenceError: reference to undefined property 0
console.debug: Conversations.AssistantUI: "Intercepted message load," 1 "message(s) selected"
JavaScript strict warning: jar:file:///home/manu/.thunderbird/eri3gju1.default/extensions/gconversation@xulforum.org.xpi!/experiment-api/msgWindowApi.js, line 441: ReferenceError: reference to undefined property "_windowId"
console.error: WebExtensions: 
  Message: TypeError: win.Conversations is undefined
  Stack:
    summarizeThreadHandler/_summarizeThread_patched/</<@jar:file:///home/manu/.thunderbird/eri3gju1.default/extensions/gconversation@xulforum.org.xpi!/experiment-api/msgWindowApi.js:491:1

console.debug: Conversations.AssistantUI: "Intercepted message load," 1 "message(s) selected"
console.error: WebExtensions: 
  Message: TypeError: win.Conversations is undefined
  Stack:
    summarizeThreadHandler/_summarizeThread_patched/</<@jar:file:///home/manu/.thunderbird/eri3gju1.default/extensions/gconversation@xulforum.org.xpi!/experiment-api/msgWindowApi.js:491:1

console.debug: Conversations.AssistantUI: "Intercepted message load," 2 "message(s) selected"
JavaScript strict warning: chrome://conversations/content/vendor/react-redux.js, line 1: ReferenceError: reference to undefined property "$$typeof"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 58: ReferenceError: reference to undefined property "childContextTypes"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 79: ReferenceError: reference to undefined property "type"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 127: ReferenceError: reference to undefined property "__reactInternalSnapshotBeforeUpdate"
JavaScript strict warning: chrome://conversations/content/vendor/react.js, line 15: ReferenceError: reference to undefined property 0
console.debug: Conversations.AssistantUI: "Intercepted message load," 1 "message(s) selected"
console.error: WebExtensions: 
  Message: TypeError: win.Conversations is undefined
  Stack:
    summarizeThreadHandler/_summarizeThread_patched/</<@jar:file:///home/manu/.thunderbird/eri3gju1.default/extensions/gconversation@xulforum.org.xpi!/experiment-api/msgWindowApi.js:491:1

console.debug: Conversations.AssistantUI: "Intercepted message load," 1 "message(s) selected"
JavaScript strict warning: chrome://conversations/content/vendor/react-redux.js, line 1: ReferenceError: reference to undefined property "$$typeof"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 58: ReferenceError: reference to undefined property "childContextTypes"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 79: ReferenceError: reference to undefined property "type"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 127: ReferenceError: reference to undefined property "__reactInternalSnapshotBeforeUpdate"
JavaScript strict warning: chrome://conversations/content/vendor/react.js, line 15: ReferenceError: reference to undefined property 0
console.debug: Conversations.AssistantUI: "Intercepted message load," 1 "message(s) selected"
JavaScript strict warning: chrome://conversations/content/vendor/react-redux.js, line 1: ReferenceError: reference to undefined property "$$typeof"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 58: ReferenceError: reference to undefined property "childContextTypes"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 79: ReferenceError: reference to undefined property "type"
JavaScript strict warning: chrome://conversations/content/vendor/react-dom.js, line 127: ReferenceError: reference to undefined property "__reactInternalSnapshotBeforeUpdate"
JavaScript strict warning: chrome://conversations/content/vendor/react.js, line 15: ReferenceError: reference to undefined property 0
```

**Comment by Standard8** [comment] 2020-06-14 11:31
> Sorry, it seems I was wrong. I click pause but the debugger is not able to stop it.

That's a shame.

> Maybe the "Conversations.AssistantUI: Document is not ready (uninitialized), waiting..." is a hint?

As it is own its own, this is probably just a non-mail window pane that opens, e.g. the error console. We don't log a matching item in that case - I'm actually going to remove that log as it isn't really useful now.

> I disabled all addons except Lightning and Google provider and it still freezes. I noticed some additional strange behaviors. Emails not displaying while the console shows:

That looks like Conversations got badly reloaded or something. Presumably restarting would have helped.

How is it going with other add-ons disabled? My only other thought is that I try doing a special version with absolutely loads of logging to try and narrow it down a bit.

**Comment by MLopez-Ibanez** [comment] 2020-06-14 22:55
> How is it going with other add-ons disabled? My only other thought is that I try doing a special version with absolutely loads of logging to try and narrow it down a bit.

It still freezes with everything disabled except for Lightning and Google Calendar Provider. I haven't tried to disable those.

**Comment by MLopez-Ibanez** [comment] 2020-06-15 12:16
Hi Mark,

Have you changed something in 3.1.9? I let it run until the point where it normally gets OOM killed, however, this time something happened, when it was about to get killed, the memory was released and it unfroze.

**Comment by MLopez-Ibanez** [comment] 2020-06-15 12:41
From the moment it freezes (last two messages) to the moment it unfreezes, these are the messages in the Error console:

```
SyntaxError: An invalid or illegal string was specified mailWidgets.js:661
SyntaxError: An invalid or illegal string was specified menulist-addrbooks.js:11
Conversations.Conversation: Updating conversation 52 global state... conversation.js:448:9
Conversations.Conversation: Removing message 
Object { _msgHdr: XPCWrappedNative_NoHelper, _id: 59, _domNode: null, _snippet: "test", _conversation: {…}, _date: "13:33", _from: {…}, _realFrom: "", _to: (1) […], _cc: [], … }
conversation.js:604:9
Conversations.AssistantUI: Intercepted message load, 1 message(s) selected 2 msgWindowApi.js:601:11
window.controllers/Controllers is deprecated. Do not use it for UA detection. fetch>UID>.INBOX>204
window.controllers/Controllers is deprecated. Do not use it for UA detection. blank
Lightning: [calSleepMonitor] Sleep cycle detected, notifying observers. calSleepMonitor.js:25
ReferenceError: reference to undefined property "message" conversation.js:607:55
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 3 folderDisplay.js:2673:9
DeleteOrMoveMsgCompleted folder:Inbox
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. SearchDialog.xul
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 2 messenger.xul
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 3 folderDisplay.js:2673:9
FolderLoaded folder:Deleted
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 2 messenger.xul
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. folderDisplay.js:990:6
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 2 messenger.xul
FolderLoaded folder:Drafts
Conversations.AssistantUI: New conversation: 53 Old conversation: 52 msgWindowApi.js:493:15
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. messenger.xul
Conversations.AssistantUI: New conversation: 54 Old conversation: 53 msgWindowApi.js:493:15
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 2 messenger.xul
TypeError: "aObj.top is undefined"
    topMail3Pane chrome://conversations/content/modules/misc.js:93
    ViewWrapper chrome://conversations/content/modules/conversation.js:132
    _filterOutDuplicates chrome://conversations/content/modules/conversation.js:562
    _whenReady chrome://conversations/content/modules/conversation.js:550
    onQueryCompleted chrome://conversations/content/modules/conversation.js:540
conversation.js:542:17
Conversations.Conversation: Outputting 
Array [ "GF" ]
conversation.js:718:9
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. messenger.xul
FolderLoaded folder:Deleted
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. messenger.xul
TypeError: "this._htmlPane.conversationDispatch is not a function"
    dispatch chrome://conversations/content/modules/conversation.js:251
    _outputMessages chrome://conversations/content/modules/conversation.js:774

FolderLoaded folder:Inbox
FolderLoaded folder:Deleted
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. messenger.xul
FolderLoaded folder:Inbox
FolderLoaded folder:Deleted
XUL box for statusbarpanel element contained an inline #text child, forcing all its children to be wrapped in a block. 2 messenger.xul
```

**Comment by groualland** [comment] 2020-06-15 14:44
I have a very similar issue when I delete a message: thunderbird uses 100% CPU for a 1-2 minutes and lots of memory (up to 4-5GB resident) then resumes operating normally (if not killed by the OOM before). 

I can reproduce that any time I delete a message and thunderbird conversations is enabled and it doesn't crash otherwise. (I'll try with only it enabled as well.)

I have tried the following:
- enabling more logs with MOZ_LOG and gloda traces, but there is no logging activity while it is frozen.
- reducing the number of messages by purging some unneeded large folders.
- removing global-messages-db.sqlite to force an index rebuild

Nothing helped. Happy to try suggestions to help pinpoint & fix this.

**Comment by groualland** [comment] 2020-06-15 15:29
Update: I tried generating a backtrace using gdb for the main thread, and had a similar trace than MLopez-Ibanez. Looking at details in the trace I noticed:

```
#252 0x00007f70aa1ac651 in mozilla::dom::Console::MaybeExecuteDumpFunction (this=0x7f70879e9000, aCx=0x7f70a1e23000, aMethodName=..., aData=..., aStack=0x0) at /build/thunderbird-7srE_p/thunderbird-68.8.0+build2/dom/console/Console.cpp:2700
        v = {<js::RootedBase<JS::Value, JS::Rooted<JS::Value> >> = {<js::MutableWrappedPtrOperations<JS::Value, JS::Rooted<JS::Value> >> = {<js::WrappedPtrOperations<JS::Value, JS::Rooted<JS::Value> >> = {<No data fields>}, <No data fields>}, <No data fields>}, 
          stack = 0x7f70a1e23068, prev = 0x7ffe9757e240, ptr = {asBits_ = 18446218344920942560, asDouble_ = -nan(0xe21da3a4e87e0), debugView_ = {payload47_ = 37221164812256, tag_ = -4}, s_ = {payload_ = {i32_ = 978225120, u32_ = 978225120, why_ = 978225120}}}}
        jsString = {<js::RootedBase<JSString*, JS::Rooted<JSString*> >> = {<js::MutableWrappedPtrOperations<JSString*, JS::Rooted<JSString*> >> = {<js::WrappedPtrOperations<JSString*, JS::Rooted<JSString*> >> = {<No data fields>}, <No data fields>}, <No data fields>}, 
          stack = 0x7f70a1e23040, prev = 0x7ffe9757e180, ptr = 0x288e14fc4700}
        string = {<nsTAutoStringN<char16_t, 64>> = {<nsTString<char16_t>> = {<nsTSubstring<char16_t>> = {<mozilla::detail::nsTStringRepr<char16_t>> = {mData = 0x7ffe9757da74 u"\"Removing message\"", mLength = 18, 
                  mDataFlags = (mozilla::detail::StringDataFlags::TERMINATED | mozilla::detail::StringDataFlags::INLINE), mClassFlags = (mozilla::detail::StringClassFlags::INLINE | mozilla::detail::StringClassFlags::NULL_TERMINATED)}, 
                static kMaxCapacity = 1073741817}, <No data fields>}, static kStorageSize = 64, mInlineCapacity = 63, 
            mStorage = u"\"Removing message\"\000\000\000\000\xdb24靗翾\000〠ꇢ罰\000\xde80靗翾\000鞀靂᯲\000moveMessage\000鞀靂᯲\000⌀䰤皰윒\xdeb8ꔯ罰\000ﻠ臙"}, <No data fields>}
        i = 1
        message = {<nsTString<char16_t>> = {<nsTSubstring<char16_t>> = {<mozilla::detail::nsTStringRepr<char16_t>> = {mData = 0x7ffe9757db0c u"console.debug: Conversations.Conversation: \"Removing message\"", mLength = 61, 
                mDataFlags = (mozilla::detail::StringDataFlags::TERMINATED | mozilla::detail::StringDataFlags::INLINE), mClassFlags = (mozilla::detail::StringClassFlags::INLINE | mozilla::detail::StringClassFlags::NULL_TERMINATED)}, 
              static kMaxCapacity = 1073741817}, <No data fields>}, static kStorageSize = 64, mInlineCapacity = 63, mStorage = u"console.debug: Conversations.Conversation: \"Removing message\"\000⅔걅"}
        stack = <optimized out>
```
which actually is the log message from Thunderbird Conversations. I had enabled this to debug slow loading messages (fixed by removing the global index) and kept it on to debug this delete issue... and retrying with it disabled, the issue goes away !!

So far I haven't experienced freezes since I disabled it. Don't know if that helps?

PS: I'm on TB 68.0 and Conversations 3.1.9.

**Comment by MLopez-Ibanez** [comment] 2020-06-15 21:18
> So far I haven't experienced freezes since I disabled it. Don't know if that helps?

I have disabled the debug log of Conversations and no freezes in several hours.

**Comment by Standard8** [comment] 2020-06-15 21:50
Thanks for finding that! We don't need to log the full message object there, so I'll change it. No idea why that would be causing massive memory issues, but at least we know what it is now.

**Closed** 2020-06-15 22:10 UTC
Labels: bug

**Comment by Standard8** [comment] 2020-06-15 22:20
Thanks again for finding the logging issue. I run with logging on and the error console open a lot of the time, and I've never seen that :( My suspicion is it is something in how the objects are constructed on your profiles, I suspect there may be account or folder information in the object, and trying to dump all of it is proving too much.

In any case, I've now cut the debug down to logging just a minimum, so hopefully that'll be better.

I've just updated the currently-pending-review version with the patches as well, so probably in a few days it'll be out.
