### ISSUE TITLE
Unable to type in response to the quick reply box

### ISSUE THREAD

**Issue by hkmenon** [protz/thunderbird-conversations#1342] opened 2019-01-24 21:16 UTC
* **Thunderbird version: 65.0b3**
* **Thunderbird Conversation version:2.15pre**
* **Operating System:Windows 10**

**What did you do?**
Clicked on Quick Reply
**What did you expect to happen?**
(1) The Quick reply edit box to appear (2)I should be able to type in response (3) click Send.
**What actually happened?**
(1) The quick reply edit box appears but I am not able to type in my response into the edit box.

![2019-01-24_15-17-50](https://user-images.githubusercontent.com/20973420/51709131-3ea09e00-1feb-11e9-9787-13ff57f69e48.png)

**Comment by Standard8** [comment] 2019-08-25 14:44
Ah yes, quick reply hasn't been working in the post 60 builds. I've currently disabled it completely because of that, though I'm hoping to bring it back soon.

Duplicate of #1308

**Closed by Standard8** 2019-08-25 14:44 UTC
