### ISSUE TITLE
Stopped working with TB 38.6.0

### ISSUE THREAD

**Issue by radekvokal** [protz/thunderbird-conversations#1064] opened 2016-02-26 13:40 UTC
With the recent update the plugin stopped working. I'm running TB 38.6.0 on Fedora Linux with  Thunderbird Conversations 2.10.2. Plugin seems to be loaded but the Conversation interface is not working.

**Comment by rnc** [comment] 2016-02-26 13:47
Duplicate of https://github.com/protz/thunderbird-conversations/issues/1061 ?

**Closed** 2016-03-01 16:50 UTC
