### ISSUE TITLE
Display and layout of buttons could they be customized?

### ISSUE THREAD

**Issue by GitgPHub** [protz/thunderbird-conversations#1441] opened 2020-02-12 22:59 UTC
It would be really great if we could decide which buttons appear in Conversations bar and set their location. Like TB bars are customizable. Is it something that can be considered for a future release?
Thanks!

**Comment by Standard8** [comment] 2020-02-14 20:58
Duplicate of #278

**Closed by Standard8** 2020-02-14 20:58 UTC
