### ISSUE TITLE
Mac remote content privacy banner does not show `preferences` button

### ISSUE THREAD

**Issue by BrendanSimon** [protz/thunderbird-conversations#1283] opened 2018-06-19 01:17 UTC
On Mac (macOS High Sierra 10.13.5), the remote content privacy banner is shown when displaying messages, but the **`preferences` button is not shown** (which normally allows me to show remote content for the message if I choose so).

Disabling TB Conversations causes the `preferences` button to reappear.

* **Thunderbird version:** 52.8.0
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** macOS High Sierra (10.13.5)

**What did you do?**  Nothing.  It used to work ok, but now doesn't.  Presuming either an OS, TB or Conversations upgrade is the issue.

**What did you expect to happen?**  `preferences` button to be displayed as previously.

**What actually happened?**  `preferences` button does not show at all.

**Comment by Standard8** [comment] 2018-07-28 11:00
This seems like a duplicate of #1278 ?

**Comment by BrendanSimon** [comment] 2018-07-31 01:25
Yes, it does seem like a duplicate, apart from the Win v Mac platforms.

I'd probably leave this issue open (at least for now), just in case fixing the Windows case doesn't fix the Mac case.  Fingers crossed it's the same fix :)

**Comment by BrendanSimon** [comment] 2018-08-02 11:06
FYI.  Mac symptoms are similar to Windows.

- `Preferences` button does **not** show up in preview pane.
- `Preferences` button does **not** show if select "Open Message in New Tab".
- `Preferences` button **does** show if select "Open Message in New Window".
- `Preferences` button **does** show if `Conversations` extension is **disabled**.

**Comment by Standard8** [comment] 2018-08-02 12:33
It'll be the same, whatever the issue is, there's very little platform dependent code at the front end.

Duplicate of #1278

**Closed by Standard8** 2018-08-02 12:33 UTC
