### ISSUE TITLE
eMail in a TB tab is not displayed after re-start of TB

### ISSUE THREAD

**Issue by WalZyl** [protz/thunderbird-conversations#1429] opened 2020-01-18 11:45 UTC
* **Thunderbird version:** 68.4.1
* **Thunderbird Conversation version:** 3.0.10
* **Operating System:** Windows 10

**What did you do?**
Open an eMail (single one or a thread) with TB-conversations in a new TB tab. Close TB with this or another tab in focus/visible. Re-start TB
 
**What did you expect to happen?**
TB restores previous session: loads all tabs and focus/display the last active. The eMail loaded in the tab with TB-conversations is displayed.   

**What actually happened?**
TB restores all tabs and focuses to that opened before closing. The eMail (single or thread) opened with TB-conversations is NOT displayed.

This happens regardless of whether the TB-conversation tab or another one was open when closing TB.

**Comment by WalZyl** [comment] 2020-01-18 11:59
To add: there seems to be something wrong in TB - without TB-conversation enabled - too: closing TB with a tab containing an email being in focus and restarting TB, restores all tabs but not that with that email. Vice versa: closing TB with inbox tab (or Options etc.) in focus and restarting again, restores all tabs including that one, and the email is displayed (when switching to this tab).

**Comment by Standard8** [comment] 2020-01-18 15:51
Hmm, I can't reproduce this at all with Mac 10.14, Tb 68.4.1 and 3.0.10. Not the conversations bit nor the Thunderbird bit.

It does make me think a bit that timing might be wrong - Thunderbird might be attempting to restore the tabs before everything has finished starting up. I might not be seeing it on my Mac as it is likely it has a different performance profile.

I'd suggestion filing a bug at https://bugzilla.mozilla.org/ for the core Thunderbird bit, and see if we can get that fixed.

**Comment by WalZyl** [comment] 2020-01-20 17:56
Okay, it is likely that this is my issue only. However, having a very fast Win10 system with new updates, the issue remains a miracle. I did no updates to TB or Conversations. I was observing in the last days: Thunderbird without conversations seems stable now.

When using Conversations the situations appears as described, but like a lottery: sometimes loading the email in a tab after restart works as expected, but some minutes later - PC was just on its own - it does not work any more, i.e. email is not loaded after restart any more.

I suspect that - maybe/meanwhile - TB  did check for new emails and somehow re-ordered its database. Supporting this: once, after checking for new emails the issue started again immediately, being absent before.

In my feeling, there is something wrong with "timing" and also with "updating" of display/views of the database. Maybe in coincidence. 

I'm going to observe this, waiting for updates to come; the issue - as for me - isn't closed.

**Comment by Standard8** [comment] 2020-01-20 21:43
It might be interesting to leave the preferences tab open alongside some of the email ones. The preferences tab is constructed slightly differently to the email ones.

There's a few scenarios here:

* If preferences tab breaks as well, then the problem is entirely Thunderbird's. All Conversations does is set it up as per dedicated APIs, if Thunderbird doesn't register things correctly, then we can't do anything about it.
* If the preferences tab keeps on working, but the conversation emails fail, then it is likely an issue between the timing of how that part of the add-on is setup, and the timing of how Thunderbird starts. What we can do about it at this stage I don't yet know. There's a lot of work to be done on Conversations that might help, but a timescale for that I don't know.

**Comment by WalZyl** [comment] 2020-01-21 12:06
The second scenario applies. Tabs with Options, Preferences, Add-ons keep working, only tabs with conversations emails stop break. As said, this is almost random behaviour, it works some some times but break unexpectedly. And, as far as I observed, it is closely related to the "Between" column problem. I'm going to observe this, waiting for updates to come.

**Comment by fridgelord** [comment] 2020-01-22 06:55
There is also another minor bug that might be related to this issue: when you open a thread in a new tab the tab is named "Conversation reader" instead of subject of the thread as it used to be before the update. @WalZyl mentioned that for him it's random, but in my case tabs are never properly restored after a restart.

**Comment by JulienGAMartin** [comment] 2020-01-22 16:12
Same for me tab are never properly restored and tab header is "Conversation reader" instead of the subject of the email. Using TB 68.4.1 with TC 3.0.10 on Ubuntu 18.04. Seems to be new problem with the new update. Need to check

**Comment by Standard8** [comment] 2020-01-23 22:13
Please can someone add a screenshot of the tab title/contents that get displayed when this happens?

If it is just the message display but blank, please also take a look on the error console (3-bar menu -> Tools -> Developer Tools > Error Console) just after startup and/or switch to the tab and see if there's any relevant errors.

If it is an error message displayed in the tab, then I don't need the error console output.

**Comment by fridgelord** [comment] 2020-01-23 22:41
Hi, the page is blank as you can see in the shot. The only error I see is: `uncaught exception: 2147746065` from ` autosync.jsm:251:30` but have no idea if it can be relevant. It appears a few seconds after start regardless if I switch to the blank tab or not.

![image](https://user-images.githubusercontent.com/33808280/73030090-27cc9b80-3e39-11ea-9d43-56f10e3cbd11.png)

**Comment by JulienGAMartin** [comment] 2020-01-24 02:03
Same for me. Window is blank and I have the firt 2 errors after startup. When I open a new conversation tab (double click on a message then the other errors appear

![Screenshot from 2020-01-23 20-55-24](https://user-images.githubusercontent.com/10862457/73039311-7b33ef00-3e23-11ea-8ca0-295a0d286d9a.png)

**Comment by Standard8** [comment] 2020-01-24 07:46
Thank you. I've just realised that some conversation errors don't get output by default - I'm going to change that.

For now, could you try going into Tools -> Add-ons, and selecting Conversation's preferences, down the bottom is the option for debugging.

Turn that on, then restart and you should get a lot more messages out.

To copy messages, you can right-click and `Select All`, then right-click again and `Copy Message`.

You may want to turn the logging off after. It might have a slight performance impact, but only really if the console is open.

**Comment by fridgelord** [comment] 2020-01-24 09:25
First of all, the issue is also random for me now (even though no updates). But I can confirm this has something to do with loading times. Sometimes when Thunderbird starts conversation tabs are displayed right next to Inbox and Lightning tab is show with a delay as the right-most tab. In these cases conversation tabs are empty. Sometimes, however, Lightning is displayed instantaneously and is next to Inbox, and message tabs are located to the right of Lightning. Then the messages are displayed properly. In both cases tabs are named "Conversation Reader" instead of subject of the thread. 

Here's my log with debugging enabled for cases messages are not displayed (I've filtered out log category, please let me know if you need it): 

`Error: Cannot find loader for bootstrap 4 XPIProvider.jsm:1877:15 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:17 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:3 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:4 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:3 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:4 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:5 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:6 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:30 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:31 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:32 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:33 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:34 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:5 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:7 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:13 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:17 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:21 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:39 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:41 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:13 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:14 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:15 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:16 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:17 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:18 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:19 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:20 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:21 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:22 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:23 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:24 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:25 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:26 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:27 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:28 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:29 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:30 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:31 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:32 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:33 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:38 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:39 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:40 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:41 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:42 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:43 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:44 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:45 
Ignoring unrecognized chrome manifest directive 'style'. chrome.manifest:46 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:31 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:32 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:33 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:34 
Ignoring unrecognized chrome manifest directive 'overlay'. chrome.manifest:35 
NS_ERROR_FAILURE: Couldn't decrypt string 2 crypto-SDR.js:203 
NS_ERROR_FAILURE: Couldn't decrypt string 2 crypto-SDR.js:203 
NS_ERROR_FAILURE: Couldn't decrypt string 2 crypto-SDR.js:203 
ReferenceError: checkRadioControl is not defined messenger.xul:1:1 
Use of Mutation Events is deprecated. Use MutationObserver instead. calendar-views.js:97:9 
Overlays.jsm: Could not resolve 14 references 
Array(14) [ window#main-window, menupopup#menu_ToolsPopup, popup#contentAreaContextMenu, toolbarpalette#BrowserToolbarPalette, toolbarbutton#reminderFox_openButton, popup#abResultsTreeContext, toolbarbutton#reminderFox_addReminderButton.toolbarbutton-1.chromeclass-toolbar-additional, toolbarbutton#reminderFox_showCalendar.toolbarbutton-1.chromeclass-toolbar-additional, toolbarbutton#reminderFox_quickAlarmButton.toolbarbutton-1.chromeclass-toolbar-additional, toolbarbutton#reminderfox-sendPlus.toolbarbutton-1.chromeclass-toolbar-additional.reminderfox-sendPlus, … ] 
Overlays.jsm:195 
[Exception... "Component returned failure code: 0x80550005 [nsIMsgFolder.messages]"  nsresult: "0x80550005 (<unknown>)"  location: "JS frame :: chrome://messenger/content/parent/ext-messages.js :: list :: line 132"  data: no] ext-messages.js:132:1 
XML Parsing Error: not well-formed 
Location: http://tvn24bis.pl/blog-rafala-hirscha,190.xml 
Line Number 13, Column 22: blog-rafala-hirscha,190.xml:13:22`

**Comment by Standard8** [comment] 2020-01-24 09:31
Unfortunately it looks like the Logs part I'll need (there's no errors there, which is a little strange).

I believe you should be able to include them here in a collapsible form if you do something like it suggests here: https://github.com/dear-github/dear-github/issues/166#issuecomment-474665835

**Comment by fridgelord** [comment] 2020-01-24 09:53
At work currently, so can't go about checking the tags for code collapse, put the messages on pastebin instead and will edit later.

Here's the log when the messsage is restored properly:
https://pastebin.com/0mgrmmj4
And here's the one with message not displayed:
https://pastebin.com/sf7n5SpF

**Comment by Standard8** [comment] 2020-01-24 10:01
No problem, pastebin is fine really. I probably won't get to look at it in detail until later anyway.

The log when the message is not displayed seems to not have the logging turned on. Either that or Conversations has been so messed up it hasn't started properly.

**Comment by fridgelord** [comment] 2020-01-24 11:01
I poked around a little and there are two things I've noticed:
1. Conversations debugging is related to message in tab being or not being displayed (starts in cases when there is no issue with message restoring)
2. Conversations debugging and message begin displayed seems to be related to shutting down Thunderbird: if I reboot Windows without closing Thunderbird messages are restored properly and Conversations debugging starts (4 out of 4 times); if I close Thunderbird and open it again, things go wrong and the same happens even if I reboot having closed Thunderbird before.

Hope this can shed some light on the issue.

**Comment by Standard8** [comment] 2020-01-24 14:17
When it is broken, is the "Between" column available to be displayed? Just trying to narrow down what is happening.

Presumably when you reboot Windows without closing Thunderbird, then Windows auto-starts Thunderbird? If so that's definitely more like timing. Windows is likely still starting up and getting going at that stage so will slow down Thunderbird's start up

**Comment by fridgelord** [comment] 2020-01-25 10:25
When it's broken Between column always appears in the left-most position (even if it was removed or moved to another position before Thunderbird restart). When I restart Windows (or log out and log in back) Between column is not displayed if it was removed or retains its position from before restart. Definitely related the two issues are related. 

No, Thunderbird is not automatically started after reboot and there doesn't seems to be any Thunderbird process running in the background.

**Comment by fridgelord** [comment] 2020-01-25 11:02
One more thing: I've tested this on a laptop running Xubuntu 18.04 and although a restart initiated by the DE breaks tab display, Between column and debugging, if I issue a 'shutdown' command from terminal, Thunderbird restarts (in this case Thunderbird is restarted automatically by XFCE) without any of those issues present.

**Comment by Standard8** [comment] 2020-03-01 12:52
I think I just hit this and got debugging out:

```
2020-03-01 12:44:24	Conversations.Stub	DEBUG	TypeError: mainWindow.Conversations is undefined

2020-03-01 12:44:24	Conversations	DEBUG	
@chrome://conversations/content/stub.js:146:35
```

This looks like the tabs are starting up before the back-end has fully started. I think I see a way to fix this, but I need to dig into some of the older code to try and figure out why stub.js is attempting to get the `Conversations` class via `monkeyPatch`. It looks like it doesn't need to, but I just want to see if there's any reason why.

Hopefully I'll be able to get this fixed in the next few days.

**Comment by Standard8** [comment] 2020-03-01 20:59
I landed a patch that I thought fixed this but doesn't quite. Still a bit more to do.

One question for those that leave conversation tabs open: has it always been the case that if you have the main tab selected on startup, it will render the messages of the open tabs in the preview section?

**Comment by WalZyl** [comment] 2020-03-02 08:50
On my system (TB 68.5.0, Conversations 3.0.16, Win10 newest) the messages in open tabs are not rendered when TB has been closed and restarted subsequently. This is in dependent of the tab (main or one of that with messages in it) which is selected while closing TB.

Another observation: when opening a message in a new tab, now the subject is displayed as tab's title. However, after closing and re-starting TB the tab's title is blank (nothing).

**Comment by Standard8** [comment] 2020-03-02 09:16
I think I asked the wrong question, but I've just remembered to try it in TB 60 and something similar was happening, so I'm not too worried in that case (although it's a bug I'd still hope to be able to fix at some stage).

I'll see if I can get time to try out my latest additional fix later, and hopefully that'll work.

**Closed** 2020-03-07 16:26 UTC
Labels: investigate, thunderbird issue

**Comment by Standard8** [comment] 2020-03-08 13:01
Just to note, 3.0.17 was approved a few hours ago, so this should be available now.
