### ISSUE TITLE
Double-Click / Enter does not open message in Conversation Reader

### ISSUE THREAD

**Issue by chrpos** [protz/thunderbird-conversations#1413] opened 2020-01-10 12:38 UTC
* **Thunderbird version:**  68.3.1
* **Thunderbird Conversation version:** 3.0.3
* **Operating System:** Windows 10

**What did you do?**
Update to TB 68, Update to TB Conversations 3.0.3

**What did you expect to happen?**
Double-click a message and open the message in the Conversations Reader window.

**What actually happened?**
Since updating, message do not open the Conversations Reader by double-click or [ENTER]. They are shown in the message preview window, though. From there, clicking the icon "Show conversation in new tab" then the Conversations Reader opens inside a popup window.

**Comment by Standard8** [comment] 2020-01-10 13:37
Thanks for the report. I've already fixed this and pushed a version to the add-ons site, but we're current awaiting approval for it. I'm hoping it'll be reviewed later today.

This is a duplicate, but we've had a few, so I'll leave it open so other people can see as well.

**Comment by Standard8** [comment] 2020-01-10 13:37
Duplicate of #1407

**Comment by chrpos** [comment] 2020-01-10 14:51
Thank's for your answer!

**Comment by Standard8** [comment] 2020-01-10 17:23
Good news, this was approved an hour ago, so it should be available via Three-bar-menu -> Add-ons -> Add-ons, then click on Extensions, followed by the cog symbol and check for updates.

You may need to restart Thunderbird for it to full take effect.

**Comment by Standard8** [comment] 2020-01-10 17:24
Duplicate of #1406

**Closed by Standard8** 2020-01-10 17:23 UTC

**Comment by chrpos** [comment] 2020-01-10 20:04
Nice, I can confirm it works. Thank you!

**Comment by WalZyl** [comment] 2020-01-10 21:57
Neither does the pane below (F8) work, nor does the pane work after double-clicking: it opens a new tab BUT the content of emails is NOT displayed. 

Sorry to say, a complete disaster!

It is better to roll back to  <3.0. Especially since > 3.0 has no new functionality.

Win10, TB 68.4.1., Conversations 3.0.6

**Comment by Standard8** [comment] 2020-01-10 22:57
> Neither does the pane below (F8) work, nor does the pane work after double-clicking: it opens a new tab BUT the content of emails is NOT displayed.

> Sorry to say, a complete disaster!

Sorry to say but it works fine here. Seeing as the original reporter agreed that it works now, this means that your issue is unlikely to be this one, so maybe you could file a new issue please?

It would be useful if you could check the error console (Three bar menu -> Tools -> Developer Tools -> Error Console) for any error messages. This check needs to be just after startup, and as you click on the first couple of messages.

**Comment by WalZyl** [comment] 2020-01-11 19:52
Although closed, I'm posting here:
* somehow my yesterdays post arrived two hours after the closure of the issue (this to explain ...)
* Since at that time TB conversations (3.0.6 in TB 68.4.1) worked here so disastrous, it couldn't be a bug.
  Error console was not throwing/displaying an error!
  After giving disabling/enabling a trail (which doesn't help), I removed and re-install the extension.
  SUCCESS.
* Just to mention: I'm using TB conversations since the very, very first release; always updating only.
   TB conversations 3.0.3 didn't work with double-click in order to open a new tab in TB 68.3.
   Yesterday, (10.01.20) I updated TB to 68.4.1 first, THEN TB Conversations to 3.0.6. Nothing else!
   This was giving the result described in my post: TB conversations was not functional at all.

Reporting this, I like to express my gratitude to your work regarding the maintenance and taking care for this add-on. I'm like on turkey without it. Thank you so much!

There is _another issue_, someone will report on it certainly: the column "Between" is appearing after TB restart although it has been disabled before. But only, if TB is closed with the main pane in focus. 

Regards. All the best!
