### ISSUE TITLE
Conversations breaks indexer: JS error

### ISSUE THREAD

**Issue by exteon** [protz/thunderbird-conversations#1219] opened 2017-08-05 17:47 UTC
Hi,
Lately this error occurs for me when turning on Conversations:

```
TypeError: this.activeIterator.return is not a function indexer.js:897:7

pop: function gloda_index_callbackhandle_pop() {
     this.activeIterator.return();
```

This breaks indexing (it gets stuck at "Determining which messages to index in Sent".

**Comment by arty-name** [comment] 2017-08-06 22:03
I guess it’s a duplicate of #1184

**Comment by Standard8** [comment] 2017-08-07 11:27
Yep, duplicate of #1184

**Closed by Standard8** 2017-08-07 11:27 UTC
