### ISSUE TITLE
Invitations Accept/Decline Buttons missing (2.14.5)

### ISSUE THREAD

**Issue by Stefan1232** [protz/thunderbird-conversations#1325] opened 2018-11-22 08:11 UTC
* **Thunderbird version: 60.3.1 (32bit)**
* **Thunderbird Conversation version: 2.14.5**
* **Operating System: Windows 10**

**What did you do?**
I got an email with an invitation attached. 

**What did you expect to happen?**
Without conversation activated, Thunderbird asks me to accept or decline the invitation.
![invatationwithoutconversation](https://user-images.githubusercontent.com/45255111/48889522-77c76100-ee36-11e8-80a1-9eac01f5c263.PNG)

**What actually happened?**
With conversations activated Thunderbird doesn't ask me any more what I would like to to with the Invitation.
![invatation](https://user-images.githubusercontent.com/45255111/48889187-44d09d80-ee35-11e8-9518-2575f3125bff.PNG)

I found Issue  #1292, which should have been fixed in 2.14.3, but apperantley it doesn't work in 2.14.5

**Comment by vimmerru** [comment] 2019-03-07 09:26
I can confirm this:

After enabling conversations If email message contain any html in addition to ics file multi-part Thunderbird doesn't recognize email as an invitation. It is reproduced in both conversation view and classic view. Disabling conversation immediately solves the issue. Most probably because conversations modifies email body before lighting invite parser gets access to the message.

This days 90% of invites contain additional html part as the most of clients and cloud services add this. It is serious blocker for me and my organization to use conversations. I can help in fix, but i don't know how this infrastructure work in details.

**Comment by ehsjoar** [comment] 2019-11-06 15:57
I also have this problem.
Thunderbird: 60.9.0 (64bit)
Conversation 2.14.7
Lightning 6.2.9

I love TB Conversation but had to disable it as I need to be able to see invites.

**Comment by Standard8** [comment] 2020-01-12 18:51
I believe this is fixed in the latest version of Conversations. We did a rewrite recently and these were working when I tested the lightning bar.

**Closed by Standard8** 2020-01-12 18:51 UTC
Labels: investigate
