### ISSUE TITLE
Conversations are not being threaded in the Unified Inbox

### ISSUE THREAD

**Issue by saiarcot895** [protz/thunderbird-conversations#1503] opened 2020-06-18 01:07 UTC
* **Thunderbird version:** 68.7.0
* **Thunderbird Conversation version:** 3.1.13
* **Operating System:** Ubuntu (KDE) 19.10

**What did you do?**
Conversations auto-updated to 3.1.13 from 3.0.18 (I think) after initially updating to 3.1.6

**What did you expect to happen?**
Things to continue working.

**What actually happened?**
1. Unified Inbox disappeared. I was able to get this back after rerunning the Setup Assistant from the addon preferences.
2. In the unified inbox, conversations are no longer threaded, and are listed as individual messages. However, after opening up a message, the full conversation is there.
3. Messages initially get marked as read after opening them. After a couple minutes, however, they get marked as unread again. (I'm not sure this is an addon problem, though, but I didn't see this behavior prior to the updates.

**Comment by Standard8** [comment] 2020-06-18 07:11
> * Unified Inbox disappeared. I was able to get this back after rerunning the Setup Assistant from the addon preferences.

As you've already commented, this sounds like #1501. Note, you can simply go to the Three-bar-Menu -> View -> Folders -> Unified to change this.

> * In the unified inbox, conversations are no longer threaded, and are listed as individual messages. However, after opening up a message, the full conversation is there.

This is probably the same issue as the first. You can change this by Three-bar-menu -> View -> Sort by -> Threaded.

> * Messages initially get marked as read after opening them. After a couple minutes, however, they get marked as unread again. (I'm not sure this is an addon problem, though, but I didn't see this behavior prior to the updates.

This is a problem in the older 6.x.x versions of Thunderbird, there was a bug in the API that Conversations is now using to mark as read. Please update to the latest version of Thunderbird (68.9.0).

**Comment by Standard8** [comment] 2020-06-18 07:11
Duplicate of #1501

**Closed by Standard8** 2020-06-18 07:11 UTC
