### ISSUE TITLE
Attachements drag and drop issue

### ISSUE THREAD

**Issue by merlin-new** [protz/thunderbird-conversations#1438] opened 2020-02-05 16:00 UTC
* **Thunderbird version: 68.4.2 (32-Bit)**
* **Thunderbird Conversation version: 3.0.11**
* **Operating System: Win 10 Pro**

**What did you do? Tried to drag a pdf attachement to desktop (download), tried to drag a pdf and drop a pdf attached to an Email to a new Message**

**What did you expect to happen? That pdf can be dragged and dropped to desktop or a 'new message window'**

**What actually happened? showed a symbol 'forbidden (no parking road sign)**

**Comment by Standard8** [comment] 2020-02-05 16:02
Duplicate of #1418

**Closed by Standard8** 2020-02-05 16:02 UTC

**Comment by merlin-new** [comment] 2020-02-05 16:26
Sorry! Hope it can be fixed in teh near future! Thanks
