### ISSUE TITLE
Can't see Replies in Conversations (due to TB Update) -- When Will It Be Fixed?

### ISSUE THREAD

**Issue by koolx** [protz/thunderbird-conversations#1192] opened 2017-05-17 21:29 UTC
With the latest version of thunderbird I can't see my replies in the conversations. When will you fix this?

**Comment by rnc** [comment] 2017-05-18 06:05
This sounds like a duplicate of #1184  ; have you tried applying the patch from #1189 ?

**Comment by koolx** [comment] 2017-05-18 14:38
Hi rnc. Could you please show me how to install this patch?

**Comment by rnc** [comment] 2017-05-18 14:57
Stop thunderbird. Then I opened  `$HOME/.thunderbird/<profile>/extensions/<thunderbird xpi e.g. gconversation@xulforum.org.xpi>` in emacs then edited `modules/plugins/glodaAttrProviders.js` as per the diff. Finally start thunderbird.

**Comment by rajeshstarlite** [comment] 2017-05-19 11:27
@rnc I had the same problem as @koolx  and I tried #1189 fix but unfortunately it didn't work.

**Comment by rnc** [comment] 2017-05-19 12:11
@rajeshstarlite  Have you commented on 1184 and 1189 to update them ? 
@koolx It might be useful to close this in favour of 1184 as that has more discussions on it?

**Comment by kvelakur** [comment] 2017-05-19 13:51
I have the same issue. There is also something wrong with the colour scheme, the panes in the conversation have a grey border them.

**Comment by tonyralmeida** [comment] 2017-05-20 11:24
The patch did it. Indexing is working properly again. Thx!

**Comment by koolx** [comment] 2017-05-20 18:56
@rnc, I'm confused as to how to add this patch. I opened up gconversation@xulforum.org.xpi in emacs. I scrolled down to: modules/plugins/glodaAttrProviders.js. But then thats it. What do I do next?? What are the exact steps to take?

@tonyralmeida which pach did you use?

**Comment by rnc** [comment] 2017-05-20 19:27
@koolx You need to edit the glodaAttrProviders to apply the diff and then save it.

**Comment by koolx** [comment] 2017-05-20 20:43
@rnc I really dont know what youre talking about. When I open the file I scroll to the line it states: modules/plugins/glodaAttrProviders.js. Theres no way to edit this. its just a line among other lines in the file.

**Comment by rnc** [comment] 2017-05-20 21:31
@koolx For me, opening the xpi gives me a zip archive buffer from which each file can be opened, edited and saved. I suggest you try the pre-patched version mentioned in the comments in 1184.

**Comment by tonyralmeida** [comment] 2017-05-21 22:51
@koolx, I just read your message. I followed @rnc indications posted in this thread and edited the file modules/plugins/glodaAttrProviders.js accordingly to fix #1184 .

**Comment by rajeshstarlite** [comment] 2017-05-22 04:47
Yes @rnc, I posted comment on 1184 and 1189. Please help us @protz

**Comment by rajeshstarlite** [comment] 2017-05-22 12:37
@kroka Thank you very much. The steps I followed:

(1) I have installed the patched extension provided by @BelzebubsGrandson [#1184](https://github.com/protz/thunderbird-conversations/issues/1184#issuecomment-302261536) ((gear icon) > install from file in the add-on manager).
(2) Forced a rebuild of the global database by deleting the global-messages-db.sqlite (https://support.mozilla.org/en-US/kb/rebuilding-global-database)

Now Thunderbird started rebuild of the global database and all works fine now. Cheers!

**Comment by JavaWeasel** [comment] 2017-05-30 01:49
Patch #1184 and global-messages-db.sqlite delete & rebuild worked here. Win 10-Creators.  A note for @koolx and others: you can rename the gconversation@xulforum.org.xpi file to gconversation@xulforum.org.zip and open it with your zip manager. Extract then edit modules/plugins/glodaAttrProviders.js. Update the zip file with your edited .js file. Rename back to .xpi.

**Comment by koolx** [comment] 2017-05-30 02:06
@JavaWeasel,

I already apploed the patch from #1184. But are you saying I should have deleting  global-messages-db.sqlite? 

I'm confused about your suggestion of editing, modules/plugins/glodaAttrProviders.js. What should I edit it to?? This is the most confuding part!!

**Comment by JavaWeasel** [comment] 2017-05-30 04:38
@koolx ,

I apologize if I'm breaking this down too much. But, if you already applied the patch, you *should* be done already. Of course, do the following at your own risk and make backups of files before you edit. 

If anyone else finds errors below, please give a shout.

Before you start, close Thunderbird.
Step 1:
Find your  gconversation@xulforum.org.xpi file. 
On windows 10, this is located in C:\Users\<user name here>\AppData\Roaming\Thunderbird\Profiles\<Your default T-bird profile>\extensions\   
On Unix-y systems/ this should be <your home folder>\.thunderbird\<your default T-bird profile>\extensions\
Step 2: 
On windows, rename the gconversation@xulforum.org.xpi to gconversation@xulforum.org.zip. This will allow you to open the file like any other zip archive. For peace of mind, make a copy of the file before changing it.
Step 3:
Open the newly-renamed gconversation@xulforum.org.zip archive with WinRAR or WinZip or some zip manager like that. Open the "modules" folder. Then, open the "plugins" folder.
Step 4:
Drag (or extract) the glodaAttrProviders.js to your desktop or some folder where you can work on it. Leave the window with the zip file open.
Step 5:
Open the glodaAttrProviders.js with the text editor of your choice, be it notepad, UltraEdit, vim, emacs, etc.  Just as long as it saves in a plain text format. If it displays line numbers, that's good.
Step 6:
You will make four changes to the glodaAttrProviders.js file in the text editor:  Note that the only thing you will do is insert a single asterisk (*) after the word "function" in each change. If the line numbers don't match up, then you're working with a different version, and you should probably just stop and reset everything back to the way  it was.  In each change, make sure that there's a single space after the asterisk (*). This is based on the patch at https://github.com/protz/thunderbird-conversations/pull/1189/files
Begin editing:
At Line 92: Change "process: function _AlternativeSender_process " to "process: function* _AlternativeSender_process " 
At Line 125: Change "process: function _ContentType_process" to "process: function* _ContentType_process"   
At Line 157: Change " process: function _Bugzilla_process " to  "process: function* _Bugzilla_process "
At Line 193: Change "process: function _ConversationSubject_process" to "process: function* _ConversationSubject_process"
Don't change any other lines. 
That's it. Save your file.
Step 7:  
Drag (or add&update) the glodaAttrProviders.js back into the zip file in the modules\plugins folder. Overwrite the existing file inside the zip file. Close the zip program, save if it asks.
Step 8:  
Rename the gconversation@xulforum.org.zip file back to gconversation@xulforum.org.xpi
That's all. You've fixed the .xpi file.

The problem was that before the patch, Thunderbird wouldn't finish indexing.  So, the index might be corrupted as a result. To re-index all your existing messages, Mozilla suggests simply deleting the global-messages-db.sqlite file. The instructions are here: https://support.mozilla.org/en-US/kb/rebuilding-global-database

Now you can restart Thunderbird.  Thunderbird will automatically rebuild the missing database. It may take a while. From the Thunderbird menu bar, open Tools->Activity Manager to see the process of the rebuild.

It worked for me, but YMMV.

**Comment by koolx** [comment] 2017-05-30 05:49
Hi @JavaWeasel,

Well the patch is working well for me. So I dont think the extra instructions you provided would apply.

But one thing that bothers me is the military time stamped in mail. Is there a way to change it to standard time?

**Comment by rnc** [comment] 2017-05-30 06:44
@JavaWeasel  I found I had to delete the folder index files and the global database to fully fix things up ; see http://www.wordpress.lonbil.co.uk/scripts-configuration-files/rebuild-thunderbird-indexes-script/

@koolx I see in my mails something like "20/05/17 17:24" ; i.e. using the 24 hour clock - is that what you are referring to? I suspect Thunderbird might be picking it up from your locale OS settings.

**Comment by koolx** [comment] 2017-05-30 07:14
@rnc,

Yes thats what I'm referring to. But when I disable Thunderbird Conversations the date on mail headers is changed to the correct 12 hour format. So this is an issue in TO not TB.

**Comment by koolx** [comment] 2017-05-30 07:23
!!! CORRECTION !!!!

@rnc,

Sorry I had to make a correction. The time displayed in Conversations is:
"Mon, 29 May 2017 22:18:44 -0400"

I get this from clicking the 'i' inside the circle (information icon). The drop down then sbows this time format. As you can see the time shows: ''22:18:44". This needs to be fixed. And again, its not a system issue cuz I checked and the system format is showing the correct format. It's a TO issue not a TB issue.

**Comment by rnc** [comment] 2017-05-30 07:49
@koolx Ah I see, I wonder if its showing UTC. Separate issue perhaps.

**Comment by koolx** [comment] 2017-06-09 07:25
Looks like the problem has crept back. Replies have stopped being added below my recipient's responses. What do I do now?

**Comment by protz** [comment] 2017-06-11 23:16
I believe #1184 fixes it. I have posted a build at https://jonathan.protzenko.fr/thunderbird-conversations/ -- please reopen this issue if the latest build at this address doesn't help.

**Closed by protz** 2017-06-11 23:16 UTC
