### ISSUE TITLE
Thunderbirs start not maximized with Conversation active

### ISSUE THREAD

**Issue by Usabab** [protz/thunderbird-conversations#1121] opened 2016-10-05 08:16 UTC
Hello,
since about two months  when i open Thunderbird it is maximized but not entire window, black line appears at bottom:
![image](https://cloud.githubusercontent.com/assets/22633445/19105871/aae0cf98-8ae4-11e6-9fa1-0ad35096641d.png)

I tryied to delete "xulstore.json" file but nothing change...
Disable Conversation the problem not appear

Can you help me?

Thanks

**Comment by protz** [comment] 2016-12-31 16:41
Duplicate of #1075 -- any help is most welcome, and if you submit a pull request, you will get my full attention!

**Closed** 2016-12-31 16:43 UTC
