### ISSUE TITLE
Strange Pink Bar at Bottom - Can't Remove It

### ISSUE THREAD

**Issue by koolx** [protz/thunderbird-conversations#1171] opened 2017-03-24 20:02 UTC
I installed the app but theres a pink bar at the bottom that I cant remove. I dont have status bar enabled so I dont know where this is coming from. Look at the screen shot to see:

![tb error bar](https://cloud.githubusercontent.com/assets/8130105/24311547/0bcf3c58-10ab-11e7-8b44-ddc7dbac039c.jpg)

**Comment by pianoslum** [comment] 2017-03-24 20:49
What version of Tb and Conversations do you run?
Does this happen when you disable the AddOn?
Anything interesting in the error console (Ctrl + Shift + J)?

**Comment by koolx** [comment] 2017-03-24 21:13
Hi, pianoslum,
    
    I'm running latest version of TB and latest version of
    conversations, which is 2.11.4.  
    
    No, I don't see this happen when I disable the app. I also disabled
    my userChrome.css and the issue remains. Attached is screenshots of
    the error console messages.
    
    From,
    David
    
    
    
    On 3/24/2017 4:49 PM, pianoslum wrote:
    
    
      What version of Tb and Conversations do you run?
        Does this happen when you disable the AddOn?
        Anything interesting in the error console (Ctrl + Shift + J)?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/protz/thunderbird-conversations","title":"protz/thunderbird-conversations","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/protz/thunderbird-conversations"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pianoslum in #1171: What version of Tb and Conversations do you run?\r\nDoes this happen when you disable the AddOn?\r\nAnything interesting in the error console (Ctrl + Shift + J)?"}],"action":{"name":"View Issue","url":"https://github.com/protz/thunderbird-conversations/issues/1171#issuecomment-289139393"}}}

**Comment by koolx** [comment] 2017-03-24 21:25
Hi, pianoslum,

Here are the screenshots of the messages in the error console:

![error console1](https://cloud.githubusercontent.com/assets/8130105/24314181/c4627a7c-10b6-11e7-8ee0-e3b720b86f93.jpg)

![error console2](https://cloud.githubusercontent.com/assets/8130105/24314187/cdc729a0-10b6-11e7-89be-5e20fa218072.jpg)

**Comment by pianoslum** [comment] 2017-03-25 10:30
Hey, on the screenshots the pink bar is on top - is this due to the same problem?
Do you have any special (dark) the for Tb? If so, try to disable it, maybe it's not really compatible with Conversations.
What's your OS?

In the last months a lot of stuff happened on the UI-side. Maybe you can try out a nightly build of the addOn from here and see if it helps: https://jonathan.protzenko.fr/thunderbird-conversations/

If not, it will be very hard to help you, because we can't reproduce the error :-(

**Comment by koolx** [comment] 2017-03-25 22:48
Hi, pianoslum,

No that screen shot is just the error console. The pink bar is from the Windows 10 system wide. Has nothing to do with the problem. As stated my o/s is Windows 10.

And when I disable the theme the pink bar still appears. Very strange. I also disabled all the extensions minus Conversations. And the pink bar still persists. Again very strange. 

I installed your nighly version and again the pink bar is still there.

**Comment by pianoslum** [comment] 2017-03-26 10:09
So if the pink bar has the same color as your windows 10 bars, the color most likely is some system color. You could verify this by switching the windows theme.

But that the bar is always there, is strange... It looks like the status bar, but some text is missing. How does it look like when you enable the status bar?

You could try to find out the internal name of the pink bar:
Follow these instructions: https://developer.mozilla.org/de/docs/Tools/Remote_Debugging/Thunderbird
After connecting firefox to tb you have a window like this:

![](https://mdn.mozillademos.org/files/11121/browser-toolbox.png)

Click on the leftmost icon (cursor over a square) and you can select any element in your tb ui. When you select the strange pink bar, you could find out its name. Maybe some ui guy here can help you from that.
If you have some javascript or css knowledge, you can also do some debugging on your own!

**Comment by pianoslum** [comment] 2017-03-26 16:29
P.S.: Can't see anything suspicious in the error console. However one of the last entries refers to 'toolbar', maybe this could be part of the problem, but I can't tell for sure!

**Comment by msprotz** [comment] 2017-03-26 17:38
#1075?

**Comment by msprotz** [comment] 2017-03-26 17:43
Thanks for your bug report... closing in favor of #1075, which is believe is the same issue (you probably have a custom color theme, which is why the extra space is pink in your case).

**Comment by koolx** [comment] 2017-03-26 19:02
Hi, pianoslum,

I did as you asked. When I focus the Dev Tools on that pink bar Dev Tools doesn't detect it at all. As msprotz stated, this is the exact same problem as #1075. 


Hi msprotz, 

I assume youre the dev of this app. Although its my fave TB app I cant use Conversations until that bar is completely removed, sadly. It bothers the hell out of me. FYI I used DOM Inspector and when I target that element I get this...

![domi in tb](https://cloud.githubusercontent.com/assets/8130105/24334217/deb0173e-1234-11e7-80e1-e3fc8bcd55ef.jpg)

Please fix this issue. Strange that its been almost a year since this issue has been reported yet nothing has been done. Please fix soon.. thnanks!

.

**Comment by protz** [comment] 2017-03-27 07:19
You just need to resize the window then make it fullscreen again...

**Comment by koolx** [comment] 2017-03-27 20:09
protz,

No offense but I'm not going to resize then make it fullscreen every time I open TB. Thats retarded. Why dont you fix it so the bar doesnt appear anymore. Its been almost a year and something it shouldve been fixed already.

**Comment by protz** [comment] 2017-03-27 20:11
(@koolx's comment deleted because of abusive language)

**Comment by koolx** [comment] 2017-03-27 20:13
Wht exact abusive language sis I use? Are you that sensitive that you cant take criticism like a man?

**Closed** 2017-03-27 20:20 UTC

**Comment by koolx** [comment] 2017-03-28 04:08
Guess some men are not strong enuf
