### ISSUE TITLE
Conversation reader tabs are empty when restarting thunderbird

### ISSUE THREAD

**Issue by thewoosh1** [protz/thunderbird-conversations#1443] opened 2020-02-14 11:29 UTC
* **Thunderbird version:**
68.5.0
* **Thunderbird Conversation version:**
3.0.11
* **Operating System:**
Windows 10 Pro 10.0.18362

**What did you do?**
Closed thunderbird and restarted it
**What did you expect to happen?**
for conversation tabs to a) have names and b) have content
**What actually happened?**
the tabs are all named 'conversation reader' (this has been happening for a while) and they are empty (this is just the last couple of weeks)
I tried reinstalling conversation add-on but that made no difference 
PS Ihave used thunderbird on this pc for years and this is new

**Comment by Standard8** [comment] 2020-02-14 20:56
Duplicate of #1429

**Closed by Standard8** 2020-02-14 20:56 UTC
