### ISSUE TITLE
Broken in Beta 59.0b1

### ISSUE THREAD

**Issue by scheinercc** [protz/thunderbird-conversations#1267] opened 2018-02-18 03:57 UTC
* **Thunderbird version:** 59.0b1
* **Thunderbird Conversation version:** 2.13.4
* **Operating System:** macOS 10.11

**What did you do?**
Open email after updating to 59

**What did you expect to happen?**
Email gets displayed.

**What actually happened?**
<img width="640" alt="image" src="https://user-images.githubusercontent.com/817856/36348022-eb737bd4-14bb-11e8-85e0-174fe30c0fc9.png">

**Comment by karakatsanism** [comment] 2018-02-21 06:09
I am having the same problem.

**Comment by M-Falken** [comment] 2018-02-21 11:03
Hello
Same for me

**Comment by Standard8** [comment] 2018-02-21 11:14
No need for the +1s. This is a duplicate of #1255

**Closed by Standard8** 2018-02-21 11:14 UTC

**Comment by scheinercc** [comment] 2018-02-21 11:52
Thanks @Standard8
