### ISSUE TITLE
Hitting Enter Twice Creates Only 1 Spaced Line

### ISSUE THREAD

**Issue by koolx** [protz/thunderbird-conversations#1385] opened 2019-11-28 06:18 UTC
Hitting enter twice while typing a message does not create a double space line. I have to hit enter 3 times to do that. Hope you fix it. Thanks. 

I got the latest TB Convo 2.14.7 with win 10 and TB 60.9.1.

**Comment by Standard8** [comment] 2019-11-28 21:27
Duplicate of #1303

**Closed by Standard8** 2019-11-28 21:27 UTC
