### ISSUE TITLE
Conversations Fails to Create Double Lines on Clicking Return Twice

### ISSUE THREAD

**Issue by koolx** [protz/thunderbird-conversations#1328] opened 2018-12-03 04:28 UTC
When I type to reply to someone within Conversations, I cant create 2 lines when I hit enter twice. I have to hit enter 3 times to get it to do that. Is there a fix to create 2 lines when I hit enter only twice?

**Comment by Standard8** [comment] 2018-12-05 03:09
Duplicate of #1303

**Closed by Standard8** 2018-12-05 03:09 UTC
