### ISSUE TITLE
Messages not marked as read

### ISSUE THREAD

**Issue by doits** [protz/thunderbird-conversations#1201] opened 2017-06-17 19:22 UTC
I'm using current master 80bb08fb86ef22a45ad62b7703a76e38b48ab0bd and have the problem that messages are not marked as read when clicking on them (I've enabled the setting in Thunderbird, version 52.2.0).

When I go back to e4781cd92e9704235add9736f1b18a25969eec12 everything works again, so it seems the latest eslint commit b250907a30e3cb9dc7e0b708e0045a08be97d2bb broke it.

**Comment by irgendwie** [comment] 2017-07-01 09:19
I'm currently dealing with the same problem - reverting the mentioned commit (https://github.com/protz/thunderbird-conversations/commit/b250907a30e3cb9dc7e0b708e0045a08be97d2bb) also solves the problem for me.

**Comment by Standard8** [comment] 2017-07-04 07:17
@protz this seems to have been caused by changing `function()` to `function*()`, e.g. https://github.com/protz/thunderbird-conversations/commit/b250907a30e3cb9dc7e0b708e0045a08be97d2bb#diff-bbce063b41615834434e9d156de9d71eL232.

There's a message on the console about `iterator.send` being undefined in this case which comes from here: https://github.com/protz/thunderbird-stdlib/blob/c61b9cfa5b55e7eeafbf81956162ababcce06571/SimpleStorage.js#L139

Any ideas what to do here?

**Comment by doits** [comment] 2017-07-12 11:17
Just added a MR which removes those asterisks to make it work again

**Comment by Standard8** [comment] 2017-07-30 13:46
Just to note that #1201 has a fix for this, hopefully @protz can review it soon.

**Closed** 2017-08-28 16:17 UTC
Labels: bug
