### ISSUE TITLE
PDF preview not working anymore after upgrading to TB 45.0 on OSX 

### ISSUE THREAD

**Issue by opeeters** [protz/thunderbird-conversations#1086] opened 2016-05-06 16:55 UTC
Steps to reproduce:
- open message with PDF attachment in TB with Conversations installed
- click "preview" of attachment

Actual results:
- new tab opens as before, but there is no preview displayed of the PDF, only "loading" message

Expected results:
- preview of PDF (as in TB versions before 45.0) with navigation to scroll through the pages

This preview functionality is apparently part of TB Conversations and used to work very well prior to TB 45.0. I also tried with all other add-ons disabled.. same result.

**Comment by apippin** [comment] 2016-05-13 20:48
I'm seeing the same behavior with TB 45.0 on Windows 7 and RHEL6. It used to work prior to the upgrade to TB 45.0. I'm using Thunderbird Conversations vs 2.11.3. I've also tried the latest nightly build with the same results.

**Comment by Yoshi8765** [comment] 2016-05-16 18:08
I can confirm this on Win10 as well.

**Comment by nkmail** [comment] 2016-05-20 07:27
I can confirm this on Win8 as well.

**Comment by cescmari** [comment] 2016-05-20 13:12
Same on Win10 too

**Comment by bbcom77** [comment] 2016-05-20 13:35
same here
win10 64bit
TB 45

**Comment by msprotz** [comment] 2016-05-25 06:37
Please try https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ (2.11.4). Thanks!

**Comment by darrenkenny** [comment] 2016-05-25 15:34
That works for me in 48.0a2 - thanks!

**Comment by apippin** [comment] 2016-05-25 15:40
That works great for me too on 45.1.0. I really appreciate it. I don't know what I'd do without your extension and all of its great features. Thanks for maintaining it for us all!

**Comment by bbcom77** [comment] 2016-05-25 17:00
works with TB 45!
Thank you

**Comment by cescmari** [comment] 2016-05-25 21:25
Works fine
Thanks!
 

    El Miércoles 25 de Mayo de 2016 8:37, Jonathan Protzenko <notifications@github.com> escribió:
 

 Please try https://addons.mozilla.org/en-US/thunderbird/addon/gmail-conversation-view/versions/ (2.11.4). Thanks!—

**Comment by nkmail** [comment] 2016-05-26 06:00
Many thanks! really useful addon

**Comment by Halpulaar** [comment] 2016-05-27 23:16
'Morning everyone!
Sorry, it's on me: same problem still persists here, with:
Win7-64ProSP1, TB 45.1.0 portable, Thunderbird Conversations 2.11.4

Which mechanism has been changed for 2.11.4?

**Comment by protz** [comment] 2016-05-28 01:18
Have you restarted Thunderbird?

**Comment by Halpulaar** [comment] 2016-05-28 01:51
Several times...

**Comment by Halpulaar** [comment] 2016-05-28 01:56
Some other strange effect: the installation assistant stays 'occupied' after trying to 'applicate changes' (translation from German). I close it (manually) by the cross-button.

**Comment by protz** [comment] 2016-05-28 18:19
Anything in Tools > Error Console?

**Comment by Halpulaar** [comment] 2016-05-28 18:45
Fehler: Error: Encountered unsupported value type writing stack-scoped structured clone
Quelldatei: chrome://conversations/content/pdfviewer/wrapper.js
Zeile: 106
The rest is just usual cross-browser CSS warnings.

**Comment by protz** [comment] 2016-05-28 19:07
What the heck is that. Is it for all PDF's or just a few specific ones?

**Comment by Halpulaar** [comment] 2016-05-28 19:17
Haven't found any negative.
What did you change before, that helped others?
(I have technical understanding (PHP-coder...) but no practice with TB.)

**Comment by protz** [comment] 2016-05-29 16:14
Well previously I just had forgotten to package one file after I changed 
the build script.

There is probably something that changed in the underlying javascript 
engine. Perhaps cloneInto doesn't take functions anymore? You could try 
removing the offending line and see if that helps. viewer.js doesn't 
call Log anyhow.

Jonathan

**Comment by protz** [comment] 2016-12-31 16:18
Just tested on my OSX machine... things seem to work fine.

**Closed by protz** 2016-12-31 16:18 UTC
