### ISSUE TITLE
How do you fix the loading tab of the conversation 

### ISSUE THREAD

**Issue by itsdeux** [protz/thunderbird-conversations#1125] opened 2016-11-19 01:50 UTC
I've had this problem for a long time and I would hope some one can help me out here to solve this... 

The conversation that I want to have open after closing the Thunderbird, doesn't load back up. 

![thunderbird conversation tab loading](https://cloud.githubusercontent.com/assets/20030734/20452109/5d01d952-adb7-11e6-978f-c1d6389e987e.jpg)

Any help please!!!

**Comment by martinjuju** [comment] 2016-11-23 14:17
Duplicate of #1091 
see also #1123

**Comment by itsdeux** [comment] 2016-11-23 15:20
I'm fairly new to this coding thing, how would i go about doing this?

**Closed** 2016-12-31 16:44 UTC
