### ISSUE TITLE
Thunderbird crash when use conversations to open mail (with image as attachments) in ExQuilla folders

### ISSUE THREAD

**Issue by atttx123** [protz/thunderbird-conversations#1089] opened 2016-05-17 02:57 UTC
When i use conversations to open mail(with image as attachments) in ExQuilla folders, the Thunderbird crash.

test eml file: https://bugzilla.mozilla.org/attachment.cgi?id=8746409

---

  应用程序概要

```
名称: Thunderbird
版本: 45.1.0
用户代理: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Thunderbird/45.1.0
应用程序构建标识符: 20160509110721
已启用的插件: about:plugins
构建配置: about:buildconfig
内存使用: about:memory
```

  邮件和新闻帐户

```
account1:
  INCOMING: account1, , (none) Local Folders, plain, passwordCleartext

account2:
  INCOMING: account2, , (exquilla) mail.letv.com:443, SSL, passwordCleartext
  OUTGOING: , null, plain, passwordCleartext, true

account3:
  INCOMING: account3, , (imap) imap.exmail.qq.com:993, SSL, passwordCleartext
  OUTGOING: , smtp.exmail.qq.com:465, SSL, passwordCleartext, true
```

  崩溃报告

```
http://crash-stats.mozilla.com/report/index/bp-2d3c9fd3-6f19-4741-adf5-2d9bf2160512 (05/12/2016)
http://crash-stats.mozilla.com/report/index/bp-969e71db-6114-4754-8453-a22d22160510 (05/10/2016)
http://crash-stats.mozilla.com/report/index/bp-67725408-3b62-4849-b12b-fffa82160510 (05/10/2016)
http://crash-stats.mozilla.com/report/index/bp-6ce5f41c-59cf-41af-bc68-817a22160510 (05/10/2016)
http://crash-stats.mozilla.com/report/index/bp-5cf04dd1-94de-45e3-8e0c-ea49e2160506 (05/06/2016)
```

  扩展

```
ExQuilla for Microsoft Exchange, 45.0.1161, true, exquilla@mesquilla.com
Extra Format Buttons, 1.3, true, extra.format.buttons@codefisher.org
Lightning, 4.7.1, true, {e2fda1a4-762b-4020-b5ad-a41df1933103}
Markdown Here, 2.12.0, true, markdown-here@adam.pritchard
Priority Switcher, 0.6.14, true, {0D2172E4-C5AE-465A-B80D-53A840275B5E}
Show All Body Parts, 1.2, true, ShowAllBodyParts@kamens.us
Super Date Format, 1.1, true, superdateformat@buildontechnologies.com
tagsequence, 0.1, true, kintomiko@gmail.com
Thunderbird Conversations, 2.11.3, true, gconversation@xulforum.org
Enigmail, 1.9.2, false, {847b3a00-7ab1-11d4-8f02-006008948af5}
```

  修改过的重要首选项

```
名称: 值

  accessibility.typeaheadfind.flashBar: 0
  browser.cache.disk.capacity: 524288
  browser.cache.disk.filesystem_reported: 1
  browser.cache.disk.smart_size_cached_value: 358400
  browser.cache.disk.smart_size.first_run: false
  browser.cache.disk.smart_size.use_old_max: false
  extensions.lastAppVersion: 45.1.0
  font.size.variable.zh-CN: 14
  gfx.crash-guard.glcontext.appVersion: 45.0
  gfx.crash-guard.glcontext.deviceID: Gallium 0.4 on AMD PITCAIRN
  gfx.crash-guard.glcontext.driverVersion: 3.0 Mesa 10.3.2
  gfx.crash-guard.status.glcontext: 3
  javascript.allow.mailnews: false
  mail.openMessageBehavior.version: 1
  mailnews.database.global.datastore.id: bc27d16a-406a-43fd-8c49-0983b7a7728
  mailnews.database.global.views.conversation.columns: {"threadCol":{"visible":true,"ordinal":"3"},"flaggedCol":{"visible":true,"ordinal":"5"},"attachmentCol":{"visible":false…
  mailnews.database.global.views.global.columns: {"threadCol":{"visible":true,"ordinal":"3"},"flaggedCol":{"visible":true,"ordinal":"5"},"attachmentCol":{"visible":false…
  network.automatic-ntlm-auth.trusted-uris: https://mail.letv.com
  network.cookie.prefsMigrated: true
  network.predictor.cleaned-up: true
  places.database.lastMaintenance: 1463138147
  places.history.expiration.transient_current_max_pages: 104858
  plugin.importedState: true
  plugin.state.libgnome-shell-browser-plugin: 2
  plugin.state.librhythmbox-itms-detection-plugin: 2
```

  图像

```
  适配器描述: X.Org -- Gallium 0.4 on AMD PITCAIRN
  厂商 ID: X.Org
  设备 ID: Gallium 0.4 on AMD PITCAIRN
  驱动程序版本: 3.0 Mesa 10.3.2
  WebGL 渲染器: X.Org -- Gallium 0.4 on AMD PITCAIRN -- 3.0 Mesa 10.3.2
  GPU 加速窗口: 0

  AzureCanvasBackend: cairo
  AzureSkiaAccelerated: 0
  AzureFallbackCanvasBackend: none
  AzureContentBackend: cairo
  CairoUseXRender: 1
```

  JavaScript

  渐进式垃圾收集: 1

  无障碍环境

```
已激活: 0
停用无障碍功能: 0
```

  库版本

```
  预计最低版本
  正在使用版本

  NSPR
  4.12
  4.12

  NSS
  3.21.1 Basic ECC
  3.21.1 Basic ECC

  NSS Util
  3.21.1
  3.21.1

  NSS SSL
  3.21.1 Basic ECC
  3.21.1 Basic ECC

  NSS S/MIME
  3.21.1 Basic ECC
  3.21.1 Basic ECC
```

**Comment by protz** [comment] 2016-05-17 11:53
Hmm... @rkent thoughts?

**Comment by rkent** [comment] 2016-05-19 04:25
I was able to duplicate a crash with Conversations and ExQuilla. I
believe that the issue is that, in core code, we have:

nsMsgProtocol
<http://mxr.mozilla.org/comm-central/ident?i=nsMsgProtocol>::GetOriginalURI
<http://mxr.mozilla.org/comm-central/ident?i=GetOriginalURI>(nsIURI
<http://mxr.mozilla.org/comm-central/ident?i=nsIURI>* *aURI
<http://mxr.mozilla.org/comm-central/ident?i=aURI>)
*aURI <http://mxr.mozilla.org/comm-central/ident?i=aURI> = m_originalUrl
<http://mxr.mozilla.org/comm-central/ident?i=m_originalUrl> ?
m_originalUrl
<http://mxr.mozilla.org/comm-central/ident?i=m_originalUrl> : m_url
<http://mxr.mozilla.org/comm-central/ident?i=m_url>; while the
equivalent statement in SkinkGlue (which is the parent to ExQuilla) is:
*aOriginalURI = mOriginalUrl; At least at the crash I am seeing, that is
the issue, m_originalUrl null while m_url is set. I'll make the change
and post a beta for test. :rkent

**Comment by protz** [comment] 2016-05-19 23:41
Thanks for the lightning-fast investigation, Kent!

**Comment by atttx123** [comment] 2016-05-20 04:02
@rkent @protz thanks very much

**Comment by AdnanHodzic** [comment] 2016-07-15 08:56
I have same problem and my Thunderbird crashes dozen times on daily basis. I'll have to disable Conversations addon in order to read certain emails. 

I also use Exquilla (45.0.1161) and it happens with every version of Conversations (currently 2.11.4) I tried. I use Icedove (Thunderbird) 45.1.0 on Debian Stretch. 

Please let me know if I can provide you with any additional informations or logs that might help resolve this problem.

**Comment by DDCMI** [comment] 2016-07-26 13:32
having the same issue. would love to be able to use this as it makes my job SOOOOOO much easier.
thunderbird 45.2.0 on arch linux
if there is anything you need from me please ask.

**Comment by rkent** [comment] 2016-07-26 17:08
I have this issue fixed in the core code, but I have not done an
official release yet with that change.

But there is a beta available that includes the fix:

http://mesquilla.net/betas/1163/

**Comment by DDCMI** [comment] 2016-07-26 18:12
@rkent Thank you, issue is fixed with that pre-release. my day just got better

**Comment by AdnanHodzic** [comment] 2016-07-27 07:19
@rkent thanks! I can also confirm that latest "exquilla" fixed my problem as well.

**Comment by xdutaotao** [comment] 2016-07-29 02:09
@rkent Excellent work! same issue disappeared after re-install pre-release.

**Comment by vicmunoz** [comment] 2016-08-09 10:00
idem for me. Issue disappeared after beta installation

**Comment by protz** [comment] 2016-12-31 16:18
Thanks everyone for confirming this fixes the issue for you.

**Closed by protz** 2016-12-31 16:18 UTC
