### ISSUE TITLE
Right-click menu is not always displayed

### ISSUE THREAD

**Issue by jpfleury** [protz/thunderbird-conversations#1032] opened 2015-11-18 19:48 UTC
I don't know yet how to reproduce this bug (nor how to provide useful debug information), but sometimes when I click right in a message (for example over an email address in the content of a message to choose _Copy Email Address_ in the menu), the Thunderbird menu doesn't appear. Nothing happens.

The workaround I found is to click on the message header menu _more_, then choose _view using the classic reader_. A new tab is open. I don't have to do anything, I just go back to the previous tab (so the tab using the Thunderbird Conversations view), and the right-click menu appears again. This bug happens several times a day. My config:
- Thunderbird 38.3.0
- Thunderbird Conversations 2.10
- Xubuntu 15.10 64-bit

**Comment by protz** [comment] 2015-11-18 22:17
Can you clear the error console (tools > Error Console in the menus), 
then see if anything pops in there when the right-click bug occurs?

**Comment by jpfleury** [comment] 2015-11-19 20:28
The only thing that appears sometimes in the console (but rarely) is:

~~~
Horodatage : 2015-11-19 15:26:31
Avertissement : L'utilisation de « getPreventDefault() » est obsolète. Utiliser « defaultPrevented » à la place.
Fichier Source : chrome://messenger/content/jquery.js
Ligne : 3
~~~

**Comment by jpfleury** [comment] 2015-11-20 00:03
I think I've found why the warning pasted in my previous comment appears rarely in the console. Actually, it always displays in the console the first time I do a buggy right-click, then it no longer appears again for the subsequent clicks.

**Comment by protz** [comment] 2015-11-20 05:39
Version of Thunderbird, version of Conversations, any other addons installed?

**Comment by protz** [comment] 2015-11-20 05:40
Also, when the bug occurs, please open up the error console, copy/paste this:

```
top.opener.document.getElementById("multimessage").getAttribute("contextmenu")
```

hit enter, and tell me the resulting output

**Comment by jpfleury** [comment] 2015-11-20 06:10
When the bug occurs, the output of your Javascript code is `pageContextMenu`.

My config:

- Thunderbird 38.3.0
- Thunderbird Conversations 2.10
- Xubuntu 15.10 64-bit

My extensions (probably half were installed after I've started using Thunderbird Conversations and had the bug):

- Copy Sent to Current 1.1.2
- Deselect on Delete 2.0
- Expression Search / Google Mail UI 0.9
- FiltaQuilla 1.3.1
- Quicktext 0.9.11.6
- Shrunked Image Resizer 4.2.3
- Trier les dossiers manuellement 1.1

**Comment by protz** [comment] 2015-11-23 22:15
I suspect a bad interaction with some other addon. Can you try bisecting? (Disable half of them, restart, see if that fixes the problem, then go on...)

**Comment by jpfleury** [comment] 2015-11-24 19:34
OK, thanks for your answer. I'll disable addons and try to find if there's one that causes the bug. Regardless of the result, I'll come back here to share it.

**Comment by jpfleury** [comment] 2015-11-24 21:25
It was faster that I though. I can reproduce the bug with all other addons disabled and with an empty `userChrome.css`. Same warning in the console, same command output (`pageContextMenu`) and same workaround.

And for the record, the plugin Flash is disabled and I use the default Thunderbird theme.

**Comment by protz** [comment] 2015-11-24 22:19
Hmmm that's not good, and I still can't reproduce the issue on my 
machine. Which OS are you using?

**Comment by jpfleury** [comment] 2015-11-24 22:21
Xubuntu 15.10 64-bit

**Comment by darrenkenny** [comment] 2016-05-25 15:43
I see similar behaviour on Windows 8.1 too using EarlyBird (currently 48.0a2). It's something
that's  been around for a good while, but I've not been able to discover what it is that causes it. 

It usually works for a while, but then periodically stops - it only appears to be in the conversation area
since I can right-click elsewhere and still see the menu pop up.

**Comment by jpfleury** [comment] 2016-05-25 15:57
It seems to be some way related to virtual folders, as if switching to or from a virtual folder was triggering the bug.

**Comment by Standard8** [comment] 2019-10-21 22:25
Unfortunately without more information we're unlikely to be able to reproduce. Given the age of this bug I'll close it for now, but if it is still an issue, please feel free to re-open or file a new one.

**Closed by Standard8** 2019-10-21 22:25 UTC
Labels: bug, investigate
