### ISSUE TITLE
I am using thunderbird-conversations add on from last 10 days.It was working well till yesterday,but from yesterday i'am facing one problem in it.

### ISSUE THREAD

**Issue by aspconv** [protz/thunderbird-conversations#1353] opened 2019-04-16 04:44 UTC
* **Thunderbird version:**
* **Thunderbird Conversation version:**
* **Operating System:**

**What did you do?**

**What did you expect to happen?**

**What actually happened?**

**Comment by Standard8** [comment] 2019-04-18 16:53
Duplicate of #1354

**Closed by Standard8** 2019-04-18 16:53 UTC
