### ISSUE TITLE
Bump to Thunderbird 59

### ISSUE THREAD

**Issue by Mte90** [protz/thunderbird-conversations#1269] opened 2018-03-03 10:59 UTC
I am using THunderbird beta and I cannot install this extensions.
It is possible to bump the version supported?

**Comment by fllp** [comment] 2018-03-04 19:21
Conversations is not working yet in TB 59 (see #1255)

**Comment by Standard8** [comment] 2018-03-08 09:15
Duplicate of #1255

**Closed by Standard8** 2018-03-08 09:15 UTC
