### ISSUE TITLE
Conversations gets stuck with big email exchange

### ISSUE THREAD

**Issue by picom** [protz/thunderbird-conversations#1051] opened 2016-01-15 12:17 UTC
I have a long email exchange with many subjects discussing a project and, since the emails in the conversation became 25+, display is locked up and after a while the javascript not answering message window is shown.

**Comment by protz** [comment] 2016-01-18 08:42
Let's call it a duplicate of #1014 

Thanks,

Jonathan

**Closed by protz** 2016-01-18 08:42 UTC
