### ISSUE TITLE
Inline reply with r or Shift+R keyboard shortcut

### ISSUE THREAD

**Issue by orschiro** [protz/thunderbird-conversations#803] opened 2014-04-27 09:57 UTC
I noticed that here is only `Ctrl+Shift+R` to reply to a message by keyboard shortcut.

However, this opens a new compose window for the reply.

Is it possible to map `r` or `Shift+R` for inline replies?

So that the cursor automatically jumps to the reply field below the message.

Thanks for your advice!

**Comment by Standard8** [comment] 2018-06-07 19:06
Duplicate of #739

**Closed by Standard8** 2018-06-07 19:06 UTC
Labels: enhancement, minor
