### ISSUE TITLE
Drafts are not saved as Email draft

### ISSUE THREAD

**Issue by wagnerand** [protz/thunderbird-conversations#479] opened 2011-10-20 16:57 UTC
Using Thunderbird 7.0.1, when replying to mail whether I click on the "Save" button or just go to another thread, the draft is not saved as a draft in the drafts folder. This is fully reproducible, with Thunderbird Conversations being the only enabled extension.

Sometimes, but this is not fully reproducible, the draft is not even stored in the reply bot, when returning to that thread.

Especially when using multiple clients with an IMAP account, It's important to be able to start with an email in one, and finish it in another later. To achieve this, the draft should be stored in the drafts folder, so it will be transfered to the server.

**Comment by hkatkar** [comment] 2017-11-21 22:44
If auto-saving the draft is not feasible, just wanted to check if a pop-up/warning could be thrown hinting the user to save the quick reply when moving away from it.

I just do not learn to avoid clicking on a newly arrived email in another thread while working on my quick reply, and keep losing them all the time.

Sorry to resurrect an old thread and for my illiteracy. Thanks for the great add-on.

**Comment by Standard8** [comment] 2018-06-07 18:56
I can't see that this isn't a duplicate of #345, so closing out. Duplicate of #345

**Closed by Standard8** 2018-06-07 18:56 UTC
Labels: bug, significant-work
