### ISSUE TITLE
thunderbird 59+ support

### ISSUE THREAD

**Issue by PackElend** [protz/thunderbird-conversations#1280] opened 2018-05-31 19:12 UTC
I'm running TB 60 but unfortunately thunderbird-conversations isn't compatible yet.
When will it be supported

**Comment by nd-** [comment] 2018-05-31 19:31
Have you read #1255 before posting and asking "When will it be supported" ?

And specially this answer from @Standard8 : 
https://github.com/protz/thunderbird-conversations/issues/1255#issuecomment-384895760

**Comment by PackElend** [comment] 2018-05-31 20:03
Haven't found that one although I search back for a year.
Thank you for the hint

**Comment by Standard8** [comment] 2018-06-06 11:14
Duplicate of #1255

**Closed by Standard8** 2018-06-06 11:14 UTC
