### ISSUE TITLE
Blank Conversations when closing and opening thunderbird

### ISSUE THREAD

**Issue by sahil48** [protz/thunderbird-conversations#1447] opened 2020-02-25 13:33 UTC
* **Thunderbird version:** 68.5.0 (32 bit)
* **Thunderbird Conversation version:** 3.0.12
* **Operating System:** Windows 10

**What did you do?** I closed and opened Thunderbird. Thunderbird opens and shows all tabs I previously had open.

**What did you expect to happen?** I expect Thunderbird Conversation tabs to display the contents of the messages that were opened before restoring Thunderbird.

**What actually happened?** Thunderbird shows the contents of pdf attachments previously opened in a Thunderbird Conversations tab. All messages only show the link "Forward this Conversation" and none of the conversations from that Thunderbird Conversations tab. Scrolling up does nothing and clicking the link "Forward this Conversation" does not appear to do anything.

![image](https://user-images.githubusercontent.com/6100774/75251799-55df2b80-57a9-11ea-9ba8-fc8722cae83e.png)

**Comment by Standard8** [comment] 2020-02-29 09:45
Duplicate of #1429

**Closed by Standard8** 2020-02-29 09:45 UTC
