### ISSUE TITLE
Where are quick reply drafts stored?

### ISSUE THREAD

**Issue by sahil48** [protz/thunderbird-conversations#1316] opened 2018-10-15 13:56 UTC
I am using Thunderbird 60 with Thunderbird Conversations 2.14.5.

When I use quick reply to compose a message, it does not show up in the drafts folder. However, when I close and reopen the message, the quick reply still shows. Where is the quick reply located. Is there a way so that quick-replies can be auto-saved in my drafts folder until I send them?

**Comment by Standard8** [comment] 2018-10-22 18:45
The replies are currently stored in a SQLite database. Saving them to the drafts folder might be possible, but it appears that it would be a lot of work. Marking as duplicate of #345 as that's what it is closest to and where we would likely solve this issue.

Duplicate of #345

**Closed by Standard8** 2018-10-22 18:45 UTC

**Comment by mm-crj** [comment] 2019-12-06 23:09
I am on TB 70(70.0.1+build1-0ubuntu0.16.04.1) for ubuntu. The quick replies are lost as soon as I move to something else(another email). It is not retrieved as I come back to the same mail.

**Comment by Standard8** [comment] 2019-12-07 09:26
> I am on TB 70(70.0.1+build1-0ubuntu0.16.04.1) for ubuntu. The quick replies are lost as soon as I move to something else(another email). It is not retrieved as I come back to the same mail.

There is no Thunderbird 70.0 nor 70.0.1 release (see [here for official Mozilla releases](https://ftp.mozilla.org/pub/thunderbird/releases/)). That sounds like a Firefox number. If there is a Thunderbird of that number, then it is a ubuntu special build. 

If you are actually on Thunderbird 68 or later (with the 2.15.x series, the only series supported there) then Quick Reply isn't supported at the moment (#1361) due to the large amount changes needed to bring Conversations up to date. I'm hoping to fix it early in the new year.

At this stage I won't be re-opening or taking issue for older versions. The new code is highly different and unfortunately it can't be backwards compatible.
