### ISSUE TITLE
[Bug] GPG Signed Email is displayed as "decrypted".

### ISSUE THREAD

**Issue by CheariX** [protz/thunderbird-conversations#1275] opened 2018-05-07 12:41 UTC
* **Thunderbird version:**
52.7.0
* **Thunderbird Conversation version:**
2.13.4
* **Operating System:**
MacOS
* **What did you do?**
I sent three Mails encrypted with Enigmail 2.0.2 as follows:
a. Encrypted Email
b. Signed Email
c. Encrypted+Signed Email
I used "Protocol: PGP/Mime automatic"
* **What did you expect to happen?**
a. should be labeled/iconized as *decrypted*
b. should be labeled/iconized as *signed*
c. should have two labels/icons *signed* + *decrypted*
* **What actually happened?**
a. shows correctly *decrypted*
b. shows *signed* **and** *decrypted* although the message is only signed (double checked Email source code)
c. shows *decrypted* **but** *signed* is missing. I guess this is because the source code does not have a *Content-Description: OpenPGP digital signature*. The signature is embeded in *Content-Description: OpenPGP encrypted message*.

**Comment by Standard8** [comment] 2018-08-16 09:09
Duplicate of #1262

**Closed by Standard8** 2018-08-16 09:09 UTC
