### ISSUE TITLE
Don't mark as read emails of the currently selected thread if Thunderbird isn't on foreground

### ISSUE THREAD

**Issue by Porkepix** [protz/thunderbird-conversations#1471] opened 2020-04-22 11:23 UTC
* **Thunderbird version: 68.7.0**
* **Thunderbird Conversation version: 3.0.17**
* **Operating System: ArchLinux**

**What did you do?**
Nothing, just have Thunderbird opened on a thread

**What did you expect to happen?**
When a new email arrive in the currently opened thread, don't have it directly opened and marked as read

**What actually happened?**
It's marked as read immediately, so that user can easily miss out the email: notification disappear from phone and other places and user have to switch on Thunderbird and manually notice that the currently opened thread have emails marked as read but not actually read by the user.

**Comment by Standard8** [comment] 2020-05-06 08:40
Thanks for reporting, I'm starting to look at these, I've just made some changes on master for fixing issues that could happen when you selected a message thread with multiple unreads.

I'm still trying to figure out what's going on for things like these (and how we used to handle them, as I think this is probably a regression).

**Comment by Porkepix** [comment] 2020-05-06 08:49
> Thanks for reporting, I'm starting to look at these, I've just made some changes on master for fixing issues that could happen when you selected a message thread with multiple unreads.
> 
> I'm still trying to figure out what's going on for things like these (and how we used to handle them, as I think this is probably a regression).

Well, previous state (which was also a regression from before) was that new emails in the selected thread were not unfolded/opened up and user was not able to open them, the only workaround was to select another thread and re-select the one you was on.

And before that, I can't remember for sure, sadly, but I believe it needed a bit of scrolling or something to mark it as read.

**Comment by Standard8** [comment] 2020-05-06 20:36
Today I've landed 4e082b9 and 7bdba39 which I think are starting to improve things.

The first one fixes a selection issue where we were sometimes getting multiple selections notified from Thunderbird, but weren't handling it properly.

The second fixes appending messages to a thread. This was noticeably broken when adding messages to an existing thread that was expanded in the thread pane.

I think these two combined might be fixing most of the issues, but I'm still testing and observing. The first one may have been contributing to the messages getting rebuilt when receiving new messages in a thread, but I'm not 100% sure yet as I need to see it happen a few more times.

I'm also still evaluating a patch for not marking things read when we're scrolling as a result of moving to the correct message position when displaying a thread.

**Comment by Porkepix** [comment] 2020-05-06 20:49
> I'm also still evaluating a patch for not marking things read when we're scrolling as a result of moving to the correct message position when displaying a thread.

I don't get what do you meant here?

**Comment by Standard8** [comment] 2020-05-06 21:53
> > I'm also still evaluating a patch for not marking things read when we're scrolling as a result of moving to the correct message position when displaying a thread.
> 
> I don't get what do you meant here?

We have functionality to mark messages read when you scroll (for the non-automatic mark as read cases or the new messages in a thread). At the moment that seems to sometimes get triggered when displaying the messages and automatically scrolling to the correct position. I've actually seen messages toggle between unread and read on an IMAP server which I think is the combination of two mark reads happening very quickly and confusing Thunderbird (probably really a Thunderbird bug, but we shouldn't be trying to mark as read on automatic scroll anyway).

**Comment by Standard8** [comment] 2020-05-07 11:56
Ok, just seen this happen again (this is more of a note to self for later):

A new message comes in, at which point `window.MessageDisplayWidget.prototype.onSelectedMessagesChanged` gets called, because the message list has updated.

That kicks off exactly the same code as if you've changed conversation, except this is using the same messages but with the extra message tagged on. Due to treating this as a conversation switch we're collapsing everything bar the unread message and then marking it as read. That would be fine, if we were really switching the conversation.

A little later, `onItemsAdded` is received at which point we would do the right thing, but we don't do anything because the message is already in the conversation...

Not quite sure of the best way to fix this. We can't change the order of notifications as that's a Thunderbird thing. The selected messages update will come in before the global database gets updated anyway as the database takes longer (which is what drives `onItemsAdded`). Given that expanded threads seem to work fine at this point (because it doesn't alter the selection afaik), we might be able to look for when the selection is collapsed, and see if the currently selected messages are a subset of the new selection - if so, we can assume it is something being added, and treat it as we do for `onItemsAdded`.

I'll see if I can investigate handling that later.

**Comment by Standard8** [comment] 2020-05-14 20:29
Ok, I landed d82a7d7 the other day, as well as 52db1bb.

I think with both of those, we're now stable enough that we can try pushing out an update and see how things go. I've not had issues running for the last couple of days.

Overall I think our unread/read handling should now be in a much better state, though I won't be surprised if I've missed something.

I'll close this out, please file new issues for anything that happens with the new version when it is released.

**Closed by Standard8** 2020-05-14 20:29 UTC
Labels: bug
