### ISSUE TITLE
The conversation with Chinese name will have messy code.

### ISSUE THREAD

**Issue by yosaku01** [protz/thunderbird-conversations#1127] opened 2016-12-07 02:12 UTC
This phenomenon happens in ThunderBird en-us edition and Chinese edition.

**Comment by protz** [comment] 2016-12-31 16:44
Sounds like an encoding issue. Does this also happen with "view using the classic reader"?

**Comment by Standard8** [comment] 2018-06-07 19:23
I'm guessing this is a duplicate of #924 which we believe is now fixed. If it is still happening with the latest versions, please feel free to file a new issue, and please add some screenshots.

Duplicate of #924

**Closed by Standard8** 2018-06-07 19:23 UTC
Labels: investigate

**Comment by YiHui-Liu** [comment] 2022-05-07 11:16
Sorry, this issue stiil happen with chinese.
Email body display normally, and this will not happen with "view using the classic reader".
Header with this plugin:
![1651922126(1)](https://user-images.githubusercontent.com/30190271/167251933-261f34e0-5bbe-4491-8e98-a01192294614.png)
Header with classic reader:
![1651922188(1)](https://user-images.githubusercontent.com/30190271/167251958-10cb135a-f08a-429e-867a-42d2ae652a9b.png)

**Comment by Standard8** [comment] 2022-05-07 12:05
If you are saying that the name of the sender is currently broken in the latest version, then that is #1835. I've fixed the issue and posted the new version for approval, though it may take a few days before it gets approved.

**Comment by YiHui-Liu** [comment] 2022-05-07 12:07
> If you are saying that the name of the sender is currently broken in the latest version, then that is #1835. I've fixed the issue and posted the new version for approval, though it may take a few days before it gets approved.

thanks for your reply, it works for me
