### ISSUE TITLE
Please support "DarkMode".

### ISSUE THREAD

**Issue by Shitennouji** [protz/thunderbird-conversations#1349] opened 2019-02-24 14:18 UTC
Please support "DarkMode".
I am currently using "TT DeepDark 12.1.3", but the display area of "Thunderbird Conversations 2.14.7" is still the default (the background is white and the text is black). By all means, please support compatible.

Thunderbird 60.5.1 (64 bit)
Windows 10

TT DeepDark 12.1.3
https://addons.thunderbird.net/en-US/thunderbird/addon/tt-deepdark/

**Comment by Standard8** [comment] 2019-02-24 19:45
Duplicate of #1313

**Closed by Standard8** 2019-02-24 19:45 UTC
