### ISSUE TITLE
Conversations 2.8.1 not working with TB 31 and Enigmail 1.7

### ISSUE THREAD

**Issue by dm74** [protz/thunderbird-conversations#845] opened 2014-08-13 16:52 UTC
Hi, after upgrading to Conversations 2.8.1 I cannot see encrypted email... Conversations no longer asks me for the decryption password.
The only thing I can do is to open the message in the classic reader, which works as expected.

**Comment by josephlhall** [comment] 2015-01-24 20:03
Seeing this too, thanks much for the workaround that doesn't require a TB restart, @rgeddes

**Comment by josephlhall** [comment] 2015-01-24 21:13
Ok, the workaround is a bit different for me... here is what happens and what I do to get enigmail and conversations working together again:

1. Start TB.
2. It will crash, but allow you to open it anyway after clicking through a "cannot connect to the enigmail service" dialog.
3. Disable and then re-enable the conversations add-on (without restarting/quitting TB in between).
4. Then, quit and relaunch TB.

Happy to point to a crash report or whatever, if it helps.

**Comment by MartinX3** [comment] 2017-03-31 10:12
Same here:
FossaMail based on LTS Thunderbird v38.
There are some compatibility issues with conversations v2.10.2 and enigmail v1.9.6.1

Mails are sometimes not decrypted, instead, they are showing the encrypted stuff.
And the tags which are showing you if the mail is encrypted/signed are missing.
If i disable conversations, everything is working.

I already tried to deactivate the checkboxes in the wizard.
I think the problem is the conversation "view".

**Comment by Standard8** [comment] 2017-10-01 13:45
Looks like this was fixed by #1029 but didn't get closed when that was merged.

**Closed by Standard8** 2017-10-01 13:45 UTC
Labels: bug
