### ISSUE TITLE
This add-on broke the "open message in a new tab" after double click

### ISSUE THREAD

**Issue by Guillaume-Garrigos** [protz/thunderbird-conversations#1412] opened 2020-01-09 02:14 UTC
* **Thunderbird version:** 68.3.1 (32 bits)
* **Thunderbird Conversation version:** 3.0.3
* **Operating System:** Windows 10

**What did you do?**
Double-click on a message

**What did you expect to happen?**
To open it in a new tab

**What actually happened?**
Nothing. 

I precise that:
- the bug happens for non-threaded messages
- right-click > open in a new tab works fine, it is the double-click which is problematic
- everything works fine once the add-on is desactivated.

**Comment by Standard8** [comment] 2020-01-09 07:46
Duplicate of #1407

Thanks for the report. We've already fixed this under the mentioned issue and posted a new version for approval by the Thunderbird editors. Unfortunately it has taken them a little longer than normal to approve it. I'll try poking them.

**Closed by Standard8** 2020-01-09 07:46 UTC

**Comment by Standard8** [comment] 2020-01-10 17:25
Good news, this was approved an hour ago, so it should be available via Three-bar-menu -> Add-ons -> Add-ons, then click on Extensions, followed by the cog symbol and check for updates.

You may need to restart Thunderbird for it to full take effect.
