### ISSUE TITLE
Messages sent do not appear in the conversation mode

### ISSUE THREAD

**Issue by xmesmin** [protz/thunderbird-conversations#1215] opened 2017-07-28 06:12 UTC
Hello,

I downloaded this extension in order to display the messages I sent during a conversation with someone, so that I could find them easily and keep a trace of what I said.
It worked fine when I installed it, as my former messages sent and received in a conversation were efficiently gathered. Still, it does not work anymore with the message I send now : the messages sent do not appear under the replies of my colleagues...
I am currently working on thunderbird version 52.2.1 (and I may have upgraded since the time I downloaded the extension, but I do not remember...). Is the problem just due to the fact that the extension is meant to work on versions 45.0 to 48.0?

Thank you in advance.

**Comment by jfml** [comment] 2017-07-29 20:49
I'm having the same issue (TB 52.2.1 on macOS 10.12.5). This worked in the past but doesn't anymore, I can't see any of the messages I sent in conversations. I'm not 100% this is a Conversations issue since sometimes even the small reply icon is missing (see attached image). Not always though! -___- Starting TB with Addons disabled doesn't fix this problem, either.

![screen shot 2017-07-29 at 22 44 56](https://user-images.githubusercontent.com/4312909/28748130-a4a1d298-74af-11e7-9100-d234c7ab634f.jpg)

**Comment by jfml** [comment] 2017-07-29 20:51
Um, I think this a duplicate of #1207?

**Comment by xmesmin** [comment] 2017-07-30 09:15
Yes it is, I had not seen this thread on the matter. As I understand, the problem is not fixed yet, and may come from the update of thunderbird...

**Comment by Standard8** [comment] 2017-07-30 13:42
This is a duplicate of #1184 - we've landed the fix in the repository, but we're waiting for a new release to be published. Hopefully will happen soon.

**Closed by Standard8** 2017-07-30 13:42 UTC

**Comment by cleeland** [comment] 2017-08-14 17:12
>we're waiting for a new release to be published

New release of...TB  or of this extension?

**Comment by SimJoSt** [comment] 2017-09-04 09:10
A new release of this addon: https://github.com/protz/thunderbird-conversations/issues/1221#issuecomment-325578117
