### ISSUE TITLE
Junk/Spam icon disappears on thread after 5 seconds

### ISSUE THREAD

**Issue by SimJoSt** [protz/thunderbird-conversations#1237] opened 2017-09-18 15:28 UTC
* **Thunderbird version:** 52.3.0 (32-bit)
* **Thunderbird Conversation version:** 2.13.2pre
* **Operating System:** Windows 10

**What did you do?**
Clicked on an unread thread, showing it in the conversations side pane.

- thread has to contain at least two emails
- can be read or unread

Waited 5 seconds.

**What did you expect to happen?**
The junk/spam flame icon should stay no matter what.

**What actually happened?**
As soon as the thread has been open for more than 5 seconds, the spam/junk flame icon disappeared, making it impossible to mark the thread as junk/spam from the conversation pane. I still can do it from the context menu or icon in the list.

**Comment by pianoslum** [comment] 2017-09-19 16:21
I can confirm under Linux 2.13.2, even though it's more like 0.5 seconds.

**Comment by Standard8** [comment] 2017-10-01 13:43
Looks like it happens once the round-trip to the server of marking as read has happened.

**Comment by Standard8** [comment] 2017-11-03 19:30
I've taken a bit more of a look at this now, and I think it is intentional:

https://github.com/protz/thunderbird-conversations/blob/0fd9c3ff3bf338a4e726d86d544c8216fea1fc79/modules/conversation.js#L1063-L1066

The only issue here is the delay in building the conversation view, which is waiting on a response from the server.

I guess it might be possible to hide it earlier if we know there's more than one message.

**Comment by Standard8** [comment] 2020-01-12 09:15
In the latest version, we're now not showing "junk this message" straight away in the case of more than one message in the thread.

This seems to be the same as what Thunderbird does, and per my previous comment I think this makes sense. Hence closing this out.

**Closed by Standard8** 2020-01-12 09:15 UTC
Labels: bug, check-after-rewrite, minor
