### ISSUE TITLE
Message pane gets visible when opening an e-mail, although disabled via first run assistant

### ISSUE THREAD

**Issue by chrpos** [protz/thunderbird-conversations#1115] opened 2016-08-29 06:51 UTC
Windows 8.1 / Thunderbird 45.2 / Thunderbird Conversations 2.11.4
Display of the message pane has been disabled via the last entry in the config-list of first run assistant and in thunderbird main application. Action on e-mail double-click is configured to open a new window.
Nevertheless, the (preview) message pane on bottom of the main window becomes visible when I double-click an e-mail/conversation. the pane is blank though. The e-mail is opened in a new window.

**Comment by Standard8** [comment] 2020-01-12 18:48
Forward duping to #1206 which I've just closed as this no longer seems to be an issue.

**Comment by Standard8** [comment] 2020-01-12 18:48
Duplicate of #1206

**Closed by Standard8** 2020-01-12 18:48 UTC
Labels: bug
