### ISSUE TITLE
Always show remote content does not persist.

### ISSUE THREAD

**Issue by PhilThurston** [protz/thunderbird-conversations#1236] opened 2017-09-15 09:29 UTC
* **Thunderbird version:** 52.3.0
* **Thunderbird Conversation version:** 2.13.2
* **Operating System:** Windows 10 64bit

**What did you do?** 
In the default version of Thunderbird when you select an email as safe it will load the content from that domain/user from that point on. The same function while using this addon does not work.

**What did you expect to happen?**
Anytime that you select `always show remote content from user@example.com` it should save that choice for future emails.

**What actually happened?**
This preference is never actually saved. It prompts to show content and always show content every time you view the email or future emails from the same users.

**Comment by Standard8** [comment] 2017-09-15 09:48
Thank you for the report. This is a duplicate of #1151 that was fixed a couple of weeks ago but hasn't been released yet.

**Closed by Standard8** 2017-09-15 09:48 UTC

**Comment by PhilThurston** [comment] 2017-09-16 02:21
Thanks @Standard8
