### ISSUE TITLE
“Delete conversation” button makes Thunderbird close/crash

### ISSUE THREAD

**Issue by sparusaurata** [protz/thunderbird-conversations#1493] opened 2020-06-10 16:30 UTC
* **Thunderbird version: 68.8.0**
* **Thunderbird Conversation version: 3.1.6**
* **Operating System: Linux Mint 18.3**

Hi,
Since Thunderbird Conversations was updated to 3.1.6, clicking on the “Delete” button when a conversation is open causes Thunderbird to crash and to close.

- When restarting the corresponding emails aren't moved to trash.
- When launching `thunderbird` in the console and making it crash, nothing new is printed in the console.

**Comment by Standard8** [comment] 2020-06-11 09:30
I've just landed a patch which might help this, and I've put a new version of the add-on up for review.

If you want to try it early, there's a copy here: https://www.thebanners.uk/conversations-3.1.7.xpi

**Comment by sparusaurata** [comment] 2020-06-12 10:52
Thanks for the patch! I've installed id, but unfortunately the bug seems to persist... :cry:

**Comment by Standard8** [comment] 2020-06-12 10:55
Are you getting a dialog about submitting a crash report?

If so, please could you go Help -> Troubleshooting Information, and look for the "Crash Reports for the Last 3 Days" section, there should be a number of report ids, please can you paste them here.

**Comment by sparusaurata** [comment] 2020-06-12 10:58
No, there's no crash report. :confused:

**Comment by Standard8** [comment] 2020-06-12 11:02
I wonder if it is actually just closing rather than crashing.

What are your preferences set to if you go to the Display section and then Advanced (a screenshot is fine)?

**Comment by sparusaurata** [comment] 2020-06-12 11:21
Here they are (in French, let me know if something isn't clear):
![image](https://user-images.githubusercontent.com/17063513/84497617-70cda100-acaf-11ea-8d71-8eab4f3e2117.png)

**Comment by Standard8** [comment] 2020-06-14 11:44
Hmm, I've just been trying with the same settings, and I still can't reproduce :(

I can't quite see in the code how that would cause it to close either - the only thing I can think of is if it thought there was only one tab left, which clearly there shouldn't be.

**Comment by sparusaurata** [comment] 2020-06-15 09:40
Fun fact: since Thunderbird Conversations was updated to 3.1.9, Thunderbird still crashes when deleting a conversation but now it does it *after* deleting it (before, when I restarted Thunderbird, the emails were still in my inbox).

**Comment by Standard8** [comment] 2020-06-15 10:17
The 3.1.7 change I made ensured that the delete was waited on before closing the tab.

I'm not convinced this is an actual crash, as the crash reporter dialog isn't coming up. You can probably check under data choices in the advanced preferences if that's enabled or not.

If it isn't a crash, I suspect this might be a Thunderbird bug, as all we're doing is closing the tab that the message is displayed in - as it isn't the last tab in the window, Thunderbird shouldn't be closing.

**Comment by Standard8** [comment] 2020-06-15 10:30
Could you also go to the three-bar menu, select Help, then "Troubleshooting Information". Select "Copy text to clipboard", and then paste that here? That might help with diagnosing some of this.

**Comment by Standard8** [comment] 2020-06-15 22:22
Do you have debugging turned on in Conversation's own preferences?

We just saw something that was affecting delete in another issue, and the cause was the debugging information, so I'm wondering if that is the same here.

**Comment by sparusaurata** [comment] 2020-06-27 12:00
Sorry, I've missed your last messages! However 3.1.16 solves the problem, thanks a lot.

**Comment by Standard8** [comment] 2020-06-28 08:30
Not quite sure what fixed it, but I'm glad it is working now. Thanks for letting us know.

**Closed by Standard8** 2020-06-28 08:30 UTC
Labels: bug
