### ISSUE TITLE
Thunderbird Conversations not working after update

### ISSUE THREAD

**Issue by sparusaurata** [protz/thunderbird-conversations#1482] opened 2020-05-17 08:02 UTC
* **Thunderbird version:** 68.7.0
* **Thunderbird Conversation version:** 3.1.2
* **Operating System:** Linux Mint 18.2

Hi! Thunderbird Conversation was updated automatically today. Since then, conversations aren't displayed any more :
* When I open a conversation in a new tab (by double-clicking on it) the new tab is empty.
* When I display the conversation in the bottom pane, it's Thunderbird's default view that is used.

**Comment by Standard8** [comment] 2020-05-17 08:08
Duplicate of #1481

**Comment by Standard8** [comment] 2020-05-17 08:08
Please see #1481

**Closed by Standard8** 2020-05-17 08:08 UTC
