### ISSUE TITLE
Blank Preview and Blank Emails

### ISSUE THREAD

**Issue by Cicorione** [protz/thunderbird-conversations#1425] opened 2020-01-13 20:57 UTC
* **Thunderbird version: 68.4.1 (64-bit)**
* **Thunderbird Conversation version: 3.0.6**
* **Operating System: macOS Mojave 10.14.6**

**What did you do?**
Updating Thunderbird to the latest version, opening it.

**What did you expect to happen?**
Reading the emails in the side preview and in the tabbed windows.

**What actually happened?**
Thunderbird-conversation prevents to display the emails and you get a blank preview or a blank tab. I mean not header, not body, absolutely blank. The preview and the emails are displayed properly if you disable the extension.

`2020-01-13 15:51:31	Conversations.Conversation	ERROR	Error: Assert failures are fatal, man
log4moz.js:769
    append resource:///modules/gloda/log4moz.js:769
    log resource:///modules/gloda/log4moz.js:419
    error resource:///modules/gloda/log4moz.js:427
    onQueryCompleted chrome://conversations/content/modules/conversation.js:643
    AsyncFunctionNext self-hosted:839`

`2020-01-13 15:51:31	Conversations.Conversation	ERROR	
!!!!!!!!!!!!!!!!!!!!!!
    ASSERT FAILURE    
!!!!!!!!!!!!!!!!!!!!!!
Unknown value for pref expand_who
log4moz.js:769
    append resource:///modules/gloda/log4moz.js:769
    log resource:///modules/gloda/log4moz.js:419
    error resource:///modules/gloda/log4moz.js:427
    assert chrome://conversations/content/modules/log.js:17
    _tellMeWhoToExpand chrome://conversations/content/modules/conversation.js:1071
    _expandAndScroll chrome://conversations/content/modules/conversation.js:939
    _outputMessages chrome://conversations/content/modules/conversation.js:880
    _whenReady chrome://conversations/content/modules/conversation.js:653
    onQueryCompleted chrome://conversations/content/modules/conversation.js:641
    AsyncFunctionNext self-hosted:839`

**Comment by Standard8** [comment] 2020-01-13 22:18
@Cicorione thank you for the report. Do you know if there were any errors reported before those two?

**Comment by Standard8** [comment] 2020-01-13 22:48
@Cicorione also, I've made a couple of changes that I think will fix this, but it may be a day or two until it gets approved.

Could you try the version here: https://www.thebanners.uk/conversations-prefs-fix.zip

You should be able to download it and then go to Tools -> Add-on manager, select the cog icon, and select "Install add-on from File".

Restart Thunderbird once you've done that, and see if it helps.

**Comment by netstat-peanut** [comment] 2020-01-14 01:47
@Standard8 I had the same issue & found this thread when I visited to report it.  Uninstalling existing add-on and installing from the add-on download linked above solved the problem. @Cicorione thank you for reporting, and @Standard8 thanks a ton for your expeditious attention to the matter!!

**Comment by rapierbit** [comment] 2020-01-14 01:47
Can confirm the bug as described. Running High Sierra 10.13.6 and Thunderbird 68.4.1. Not sure if I'm doing it correctly, but I downloaded the zipped file from your link, and installed from file (I chose the zipped file, should I have unzipped and chosen the folder?). Restarted Thunderbird. Add-on now shows v3.0.9 Jan 13. Did not fix the issue for me.

**Comment by rapierbit** [comment] 2020-01-14 01:49
Ok yes I had to remove the previous version first before installing the add-on. That worked! Me echoes the thanks!

**Comment by netstat-peanut** [comment] 2020-01-14 01:49
@rapierbit wow, simultaneous comments!  you should select the zip file, not files extracted to a folder.  what you're describing are the exact steps i took that solved the problem for me.  check out & post your error log if possible

**Comment by Cicorione** [comment] 2020-01-14 03:21
I can try it only tomorrow I'll edit this comment when I'll do the test, thanks!

**Comment by Standard8** [comment] 2020-01-14 08:22
Thank you for the responses. Have people been on Thunderbird 68 for a while, or have you only just upgraded when you started seeing this issue? There's been lots of changes in Conversations recently.

I'm a bit worried that my fix didn't seem to work on install. I'll do an additional change to try and make it so that if prefs are bad then we at least keep working, though I'm wondering if this is something to do with Thunderbird and the add-on upgrade process.

@Cicorione please can you also check for errors just after startup

**Comment by Standard8** [comment] 2020-01-14 09:36
I've just updated the add-on to 3.0.10, and submitted it for approval, and requested quick approval. This has the fix I mentioned to not completely fall over if one of the prefs is wrong.

If anyone is reading this before upgrading, it might help my understanding if whilst in the broken state can you try these:

1. Capture Error Console logs just after startup and clicking on the first message (error console is accessible from Three-pane menu -> Tools -> Developer Tools -> Error Console).
2. Try going to Tools -> Add-ons -> Preferences, check if any of the preference's don't look right (I'm mainly thinking about the radio buttons at the top and the text box), if they aren't try setting them to a value (the text box's default is 5). If they are right, then turn on debugging at the bottom of the page, and restart and grab the logs from the error console as above.

**Comment by samim23** [comment] 2020-01-14 10:36
Had the same issue for a few days, using Linux (Ubuntu) and Thunderbird 68.2.2.
Now just uninstalled and reinstalled the conversations plugin, and everything works again. Thanks!

**Comment by rapierbit** [comment] 2020-01-14 12:40
@Standard8 For me, this issue started the moment I updated to 68.4.1. It was a couple/3 days before I could spend time troubleshooting, and that was last night, when I thought to take a chance on the forum, and lo and behold...

Other than that, Conversations had been working fine (except for the general breakage with v68). At that time, I had deferred upgrading Thunderbird for other reasons, so I was lucky in that I was only without Conversations for maybe 2 days before you had posted the new version.

Prefs appearance is fine for me (AFAICT). I'll take a look at error logs later today.

**Comment by Standard8** [comment] 2020-01-14 12:43
@rapierbit Thanks for the comment. That semi-confirms my suspicions - I think something may have been going wrong around the pref migrations and blew stuff up as a result.

No need to look at error logs unless you can reproduce it still.

**Comment by netstat-peanut** [comment] 2020-01-14 15:04
@Standard8 I had the problem on 68.3.1 so i tried upgrading to solve it, which clearly didn't work.  disabling the extension on 68.4.1 rectified it, which is when i sought out github to report it and found your fix.  hope it helps; thanks again!

**Comment by Cicorione** [comment] 2020-01-14 16:02
@Standard8 I removed the previous version and installed the one you provided above and now everything works properly, thank you very much for your great job and responsiveness!

`
2020-01-14 10:56:43	Conversations	DEBUG	Logging enabled

2020-01-14 10:56:43	Conversations.MonkeyPatch	DEBUG	startup, aReason= 1

2020-01-14 10:56:43	Conversations.MonkeyPatch	DEBUG	Document is ready...

2020-01-14 10:56:43	Conversations.MonkeyPatch	DEBUG	The window looks like a mail:3pane, monkey-patching...

2020-01-14 10:56:43	Conversations.MonkeyPatch	DEBUG	Monkey patch successfully applied.

No chrome package registered for chrome://enigmail/content/modules/constants.jsm
2020-01-14 10:56:43	Conversations.Modules.Enigmail	DEBUG	Enigmail doesn't seem to be installed...

2020-01-14 10:56:43	Conversations.Modules.Lightning	DEBUG	Lightning plugin for Thunderbird Conversations loaded!

2020-01-14 10:56:43	Conversations.Modules.DKIMVerifier	DEBUG	DKIM Verifier doesn't seem to be installed or has incompatible version.

2020-01-14 10:56:49	Conversations.MonkeyPatch	DEBUG	Document is not ready (uninitialized), waiting...

020-01-14 10:57:41	Conversations.MonkeyPatch	DEBUG	Document is not ready (uninitialized), waiting...

2020-01-14 10:59:43	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  0  message(s) selected

2020-01-14 10:59:43	Conversations.MonkeyPatch	DEBUG	Hockey-hack

2020-01-14 10:59:46	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  2  message(s) selected

2020-01-14 10:59:46	Conversations.MonkeyPatch	DEBUG	Hockey-hack

2020-01-14 10:59:46	Conversations.MonkeyPatch	DEBUG	First conversation

2020-01-14 10:59:46	Conversations.Conversation	DEBUG	Outputting [01;36mGF,[01;36mGF [00m

2020-01-14 10:59:46	Conversations.Conversation	DEBUG	2 messages in the conversation now

SyntaxError: An invalid or illegal string was specified mailWidgets.js:656
SyntaxError: An invalid or illegal string was specified menulist-addrbooks.js:11
2020-01-14 10:59:46	Conversations.MonkeyPatch	DEBUG	[01;31m Marking the whole conversation as read [00m

2020-01-14 10:59:46	Conversations.Conversation	DEBUG	[01;31m Marked as read [00m

2020-01-14 10:59:46	Conversations.Message	DEBUG	A message is selected: imap-message://dantonucci@mail.eldoradofurniture.com/INBOX#9919

2020-01-14 10:59:48	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  2  message(s) selected

2020-01-14 10:59:48	Conversations.MonkeyPatch	DEBUG	Current conversation is [01;31m 1 [00m

2020-01-14 10:59:48	Conversations.Conversation	DEBUG	Outputting [01;36mGF,[01;36mGF,[01;36mGF [00m

2020-01-14 10:59:48	Conversations.Conversation	DEBUG	3 messages in the conversation now

2020-01-14 10:59:48	Conversations.MonkeyPatch	DEBUG	[01;31m Marking the whole conversation as read [00m

2020-01-14 10:59:48	Conversations.Conversation	DEBUG	[01;31m Marked as read [00m

2020-01-14 10:59:48	Conversations.Message	DEBUG	A message is selected: imap-message://dantonucci@mail.eldoradofurniture.com/INBOX#9906

2020-01-14 10:59:48	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  1  message(s) selected

2020-01-14 10:59:48	Conversations.MonkeyPatch	DEBUG	Current conversation is [01;31m 2 [00m

2020-01-14 10:59:48	Conversations.Conversation	DEBUG	Outputting [01;36mGF [00m

2020-01-14 10:59:48	Conversations.Conversation	DEBUG	1 messages in the conversation now

2020-01-14 10:59:49	Conversations.MonkeyPatch	DEBUG	[01;31m Marking selected messages as read [00m

2020-01-14 10:59:49	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  4  message(s) selected

2020-01-14 10:59:49	Conversations.MonkeyPatch	DEBUG	Current conversation is [01;31m 3 [00m

2020-01-14 10:59:49	Conversations.Message	DEBUG	A message is selected: imap-message://dantonucci@mail.eldoradofurniture.com/INBOX#9898

2020-01-14 10:59:49	Conversations.Conversation	DEBUG	Outputting [01;36mGF,[01;36mGF,[01;36mGF,[01;36mGF [00m

2020-01-14 10:59:49	Conversations.Conversation	DEBUG	4 messages in the conversation now

2020-01-14 10:59:49	Conversations.MonkeyPatch	DEBUG	[01;31m Marking the whole conversation as read [00m

2020-01-14 10:59:49	Conversations.Conversation	DEBUG	[01;31m Marked as read [00m

2020-01-14 10:59:49	Conversations.Message	DEBUG	A message is selected: imap-message://dantonucci@mail.eldoradofurniture.com/INBOX#9903

2020-01-14 10:59:50	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  1  message(s) selected

2020-01-14 10:59:50	Conversations.MonkeyPatch	DEBUG	Current conversation is [01;31m 4 [00m

2020-01-14 10:59:50	Conversations.Conversation	DEBUG	Outputting [01;36mGF [00m

2020-01-14 10:59:50	Conversations.Conversation	DEBUG	1 messages in the conversation now

2020-01-14 10:59:50	Conversations.MonkeyPatch	DEBUG	[01;31m Marking selected messages as read [00m

2020-01-14 10:59:50	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  1  message(s) selected

2020-01-14 10:59:50	Conversations.MonkeyPatch	DEBUG	Current conversation is [01;31m 5 [00m

2020-01-14 10:59:50	Conversations.Conversation	DEBUG	Outputting [01;36mGF [00m

2020-01-14 10:59:50	Conversations.Conversation	DEBUG	1 messages in the conversation now

2020-01-14 10:59:50	Conversations.MonkeyPatch	DEBUG	[01;31m Marking selected messages as read [00m

2020-01-14 10:59:51	Conversations.MonkeyPatch	DEBUG	Intercepted message load,  1  message(s) selected

2020-01-14 10:59:51	Conversations.MonkeyPatch	DEBUG	Current conversation is [01;31m 6 [00m

2020-01-14 10:59:51	Conversations.Conversation	DEBUG	Outputting [01;36mGF [00m

2020-01-14 10:59:51	Conversations.Conversation	DEBUG	1 messages in the conversation now

2020-01-14 10:59:51	Conversations.Message	DEBUG	A message is selected: imap-message://dantonucci@mail.eldoradofurniture.com/INBOX#9926

2020-01-14 10:59:51	Conversations.MonkeyPatch	DEBUG	[01;31m Marking selected messages as read [00m

2020-01-14 10:59:52	Conversations.Conversation	DEBUG	Updating conversation 7 global state...
`

**Comment by Cicorione** [comment] 2020-01-14 16:47
> @Standard8 I had the problem on 68.3.1 so i tried upgrading to solve it, which clearly didn't work. disabling the extension on 68.4.1 rectified it, which is when i sought out github to report it and found your fix. hope it helps; thanks again!

If you just upload it doesn't work, I had to uninstall it and then reinstall it, it will apply again the changes it needs to work.

**Comment by WalZyl** [comment] 2020-01-14 17:03
@Standard8: My partial answer to you question, I reported on this issue some days ago in another - at that time already closed #1413 issue: I checked but didn't noticed anything specific errors in the Three-pane menu -> Tools -> Developer Tools -> Error Console (I didn't save that, sorry). Reporting the following from memory: radio buttons: any one was "on". The textbox was set to "20" which I set years before.

**Comment by Standard8** [comment] 2020-01-15 07:43
Just to note 3.0.10 has now been released with the additional fixes.

**Comment by jkuj6** [comment] 2020-01-15 18:02
@WalZyl Just wanted to point out that 4 days ago your comment here: https://github.com/protz/thunderbird-conversations/issues/1413#issuecomment-573348853  helped me out because i was experiencing the exact same issue, ive had conversations since the very first release, and 3.0.6 auto-update somehow messed it up.  I removed 3.0.6 and then re-installed it and i was able to view my conversations again.

Although the next releases up to 3.0.10 im sure had more improvements, the problem is now sorted either way. Thanks!

**Comment by Standard8** [comment] 2020-01-19 11:17
Reports of this have stopped coming in, and 3.0.10 seems stable, hence resolving this issue.

**Closed by Standard8** 2020-01-19 11:17 UTC
