### ISSUE TITLE
winmail.dat support (maybe via LookOut fix)

### ISSUE THREAD

**Issue by MaluNoPeleke** [protz/thunderbird-conversations#1205] opened 2017-06-26 15:51 UTC
I have seen a few closed issues regarding this already but since there is a new developer and a fixed version  (https://addons.mozilla.org/de/thunderbird/addon/lookout-fix-version/) it would be nice if winmail.dat files could be extracted on the fly in combination with the conversations addon.

**Comment by Standard8** [comment] 2017-07-30 13:56
Unfortunately I think we're still in the same position as described in #400, if the author wants to reach out to us and request specific needs, we'd gladly help, but we don't have time ourselves to try and make it work (and it looks like there's no public repo for that add-on unfortunately which makes it harder to share work).

Hence, marking as duplicate of #400.

**Closed by Standard8** 2017-07-30 13:56 UTC
